// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chat_client.proto

package webitel_chat_service_flowadapter

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// Types that are valid to be assigned to Value:
	//	*Message_TextMessage_
	Value                isMessage_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f033c3cf63e42ba, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Message) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type isMessage_Value interface {
	isMessage_Value()
}

type Message_TextMessage_ struct {
	TextMessage *Message_TextMessage `protobuf:"bytes,3,opt,name=text_message,json=textMessage,proto3,oneof"`
}

func (*Message_TextMessage_) isMessage_Value() {}

func (m *Message) GetValue() isMessage_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Message) GetTextMessage() *Message_TextMessage {
	if x, ok := m.GetValue().(*Message_TextMessage_); ok {
		return x.TextMessage
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Message) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Message_TextMessage_)(nil),
	}
}

type Message_TextMessage struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message_TextMessage) Reset()         { *m = Message_TextMessage{} }
func (m *Message_TextMessage) String() string { return proto.CompactTextString(m) }
func (*Message_TextMessage) ProtoMessage()    {}
func (*Message_TextMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f033c3cf63e42ba, []int{0, 0}
}

func (m *Message_TextMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message_TextMessage.Unmarshal(m, b)
}
func (m *Message_TextMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message_TextMessage.Marshal(b, m, deterministic)
}
func (m *Message_TextMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message_TextMessage.Merge(m, src)
}
func (m *Message_TextMessage) XXX_Size() int {
	return xxx_messageInfo_Message_TextMessage.Size(m)
}
func (m *Message_TextMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_Message_TextMessage.DiscardUnknown(m)
}

var xxx_messageInfo_Message_TextMessage proto.InternalMessageInfo

func (m *Message_TextMessage) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type Error struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f033c3cf63e42ba, []int{1}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SendMessageRequest struct {
	ConversationId       int64    `protobuf:"varint,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Messages             *Message `protobuf:"bytes,2,opt,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMessageRequest) Reset()         { *m = SendMessageRequest{} }
func (m *SendMessageRequest) String() string { return proto.CompactTextString(m) }
func (*SendMessageRequest) ProtoMessage()    {}
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f033c3cf63e42ba, []int{2}
}

func (m *SendMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageRequest.Unmarshal(m, b)
}
func (m *SendMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageRequest.Marshal(b, m, deterministic)
}
func (m *SendMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageRequest.Merge(m, src)
}
func (m *SendMessageRequest) XXX_Size() int {
	return xxx_messageInfo_SendMessageRequest.Size(m)
}
func (m *SendMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageRequest proto.InternalMessageInfo

func (m *SendMessageRequest) GetConversationId() int64 {
	if m != nil {
		return m.ConversationId
	}
	return 0
}

func (m *SendMessageRequest) GetMessages() *Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

type SendMessageResponse struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMessageResponse) Reset()         { *m = SendMessageResponse{} }
func (m *SendMessageResponse) String() string { return proto.CompactTextString(m) }
func (*SendMessageResponse) ProtoMessage()    {}
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f033c3cf63e42ba, []int{3}
}

func (m *SendMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageResponse.Unmarshal(m, b)
}
func (m *SendMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageResponse.Marshal(b, m, deterministic)
}
func (m *SendMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageResponse.Merge(m, src)
}
func (m *SendMessageResponse) XXX_Size() int {
	return xxx_messageInfo_SendMessageResponse.Size(m)
}
func (m *SendMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageResponse proto.InternalMessageInfo

func (m *SendMessageResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type WaitMessageRequest struct {
	ConversationId       int64    `protobuf:"varint,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	ConfirmationId       string   `protobuf:"bytes,2,opt,name=confirmation_id,json=confirmationId,proto3" json:"confirmation_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WaitMessageRequest) Reset()         { *m = WaitMessageRequest{} }
func (m *WaitMessageRequest) String() string { return proto.CompactTextString(m) }
func (*WaitMessageRequest) ProtoMessage()    {}
func (*WaitMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f033c3cf63e42ba, []int{4}
}

func (m *WaitMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WaitMessageRequest.Unmarshal(m, b)
}
func (m *WaitMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WaitMessageRequest.Marshal(b, m, deterministic)
}
func (m *WaitMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WaitMessageRequest.Merge(m, src)
}
func (m *WaitMessageRequest) XXX_Size() int {
	return xxx_messageInfo_WaitMessageRequest.Size(m)
}
func (m *WaitMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WaitMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WaitMessageRequest proto.InternalMessageInfo

func (m *WaitMessageRequest) GetConversationId() int64 {
	if m != nil {
		return m.ConversationId
	}
	return 0
}

func (m *WaitMessageRequest) GetConfirmationId() string {
	if m != nil {
		return m.ConfirmationId
	}
	return ""
}

type WaitMessageResponse struct {
	TimeoutSec           int64    `protobuf:"varint,1,opt,name=timeout_sec,json=timeoutSec,proto3" json:"timeout_sec,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WaitMessageResponse) Reset()         { *m = WaitMessageResponse{} }
func (m *WaitMessageResponse) String() string { return proto.CompactTextString(m) }
func (*WaitMessageResponse) ProtoMessage()    {}
func (*WaitMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f033c3cf63e42ba, []int{5}
}

func (m *WaitMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WaitMessageResponse.Unmarshal(m, b)
}
func (m *WaitMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WaitMessageResponse.Marshal(b, m, deterministic)
}
func (m *WaitMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WaitMessageResponse.Merge(m, src)
}
func (m *WaitMessageResponse) XXX_Size() int {
	return xxx_messageInfo_WaitMessageResponse.Size(m)
}
func (m *WaitMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WaitMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WaitMessageResponse proto.InternalMessageInfo

func (m *WaitMessageResponse) GetTimeoutSec() int64 {
	if m != nil {
		return m.TimeoutSec
	}
	return 0
}

func (m *WaitMessageResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type CloseConversationRequest struct {
	ConversationId       int64    `protobuf:"varint,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Cause                string   `protobuf:"bytes,2,opt,name=cause,proto3" json:"cause,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseConversationRequest) Reset()         { *m = CloseConversationRequest{} }
func (m *CloseConversationRequest) String() string { return proto.CompactTextString(m) }
func (*CloseConversationRequest) ProtoMessage()    {}
func (*CloseConversationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f033c3cf63e42ba, []int{6}
}

func (m *CloseConversationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseConversationRequest.Unmarshal(m, b)
}
func (m *CloseConversationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseConversationRequest.Marshal(b, m, deterministic)
}
func (m *CloseConversationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseConversationRequest.Merge(m, src)
}
func (m *CloseConversationRequest) XXX_Size() int {
	return xxx_messageInfo_CloseConversationRequest.Size(m)
}
func (m *CloseConversationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseConversationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CloseConversationRequest proto.InternalMessageInfo

func (m *CloseConversationRequest) GetConversationId() int64 {
	if m != nil {
		return m.ConversationId
	}
	return 0
}

func (m *CloseConversationRequest) GetCause() string {
	if m != nil {
		return m.Cause
	}
	return ""
}

type CloseConversationResponse struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseConversationResponse) Reset()         { *m = CloseConversationResponse{} }
func (m *CloseConversationResponse) String() string { return proto.CompactTextString(m) }
func (*CloseConversationResponse) ProtoMessage()    {}
func (*CloseConversationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f033c3cf63e42ba, []int{7}
}

func (m *CloseConversationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseConversationResponse.Unmarshal(m, b)
}
func (m *CloseConversationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseConversationResponse.Marshal(b, m, deterministic)
}
func (m *CloseConversationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseConversationResponse.Merge(m, src)
}
func (m *CloseConversationResponse) XXX_Size() int {
	return xxx_messageInfo_CloseConversationResponse.Size(m)
}
func (m *CloseConversationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseConversationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CloseConversationResponse proto.InternalMessageInfo

func (m *CloseConversationResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "webitel.chat.service.flowadapter.Message")
	proto.RegisterType((*Message_TextMessage)(nil), "webitel.chat.service.flowadapter.Message.TextMessage")
	proto.RegisterType((*Error)(nil), "webitel.chat.service.flowadapter.Error")
	proto.RegisterType((*SendMessageRequest)(nil), "webitel.chat.service.flowadapter.SendMessageRequest")
	proto.RegisterType((*SendMessageResponse)(nil), "webitel.chat.service.flowadapter.SendMessageResponse")
	proto.RegisterType((*WaitMessageRequest)(nil), "webitel.chat.service.flowadapter.WaitMessageRequest")
	proto.RegisterType((*WaitMessageResponse)(nil), "webitel.chat.service.flowadapter.WaitMessageResponse")
	proto.RegisterType((*CloseConversationRequest)(nil), "webitel.chat.service.flowadapter.CloseConversationRequest")
	proto.RegisterType((*CloseConversationResponse)(nil), "webitel.chat.service.flowadapter.CloseConversationResponse")
}

func init() { proto.RegisterFile("chat_client.proto", fileDescriptor_6f033c3cf63e42ba) }

var fileDescriptor_6f033c3cf63e42ba = []byte{
	// 458 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x8e, 0x13, 0x42, 0xe8, 0x18, 0x05, 0x65, 0xcb, 0xc1, 0xe4, 0x42, 0xd8, 0x4b, 0xc3, 0xc5,
	0x12, 0x81, 0x5e, 0x40, 0x5c, 0x88, 0x8a, 0xe8, 0x81, 0x8b, 0x53, 0x09, 0xd1, 0x4b, 0xb4, 0xb5,
	0x27, 0xb0, 0x92, 0xe3, 0x0d, 0xbb, 0xe3, 0x24, 0x48, 0x1c, 0x39, 0xf3, 0x0c, 0xbc, 0x04, 0xef,
	0x87, 0xb2, 0x6b, 0xa7, 0xae, 0x52, 0xe4, 0x34, 0xe2, 0xb6, 0x3b, 0x3b, 0xf3, 0xfd, 0xcc, 0x8c,
	0x0d, 0xbd, 0xf8, 0xab, 0xa0, 0x69, 0x9c, 0x4a, 0xcc, 0x28, 0x5c, 0x68, 0x45, 0x8a, 0x0d, 0x56,
	0x78, 0x25, 0x09, 0xd3, 0x70, 0xf3, 0x14, 0x1a, 0xd4, 0x4b, 0x19, 0x63, 0x38, 0x4b, 0xd5, 0x4a,
	0x24, 0x62, 0x41, 0xa8, 0xf9, 0x1f, 0x0f, 0x3a, 0x1f, 0xd1, 0x18, 0xf1, 0x05, 0x59, 0x17, 0x9a,
	0x32, 0x09, 0xbc, 0x81, 0x37, 0x6c, 0x45, 0x4d, 0x99, 0x30, 0x06, 0xf7, 0xe8, 0xfb, 0x02, 0x83,
	0xe6, 0xc0, 0x1b, 0x1e, 0x45, 0xf6, 0xcc, 0x2e, 0xe1, 0x21, 0xe1, 0x9a, 0xa6, 0x73, 0x57, 0x13,
	0xb4, 0x06, 0xde, 0xd0, 0x1f, 0x9d, 0x86, 0x75, 0x44, 0x61, 0x41, 0x12, 0x5e, 0xe0, 0x9a, 0x8a,
	0xf3, 0x87, 0x46, 0xe4, 0xd3, 0xf5, 0xb5, 0xff, 0x0c, 0xfc, 0xca, 0xab, 0xa5, 0xc7, 0x35, 0x59,
	0x41, 0x1b, 0x7a, 0x5c, 0xd3, 0xbb, 0x0e, 0xb4, 0x97, 0x22, 0xcd, 0x91, 0xbf, 0x80, 0xf6, 0x99,
	0xd6, 0x4a, 0x57, 0x44, 0x1f, 0x59, 0xd1, 0x01, 0x74, 0x4a, 0x6d, 0x4e, 0x77, 0x79, 0xe5, 0x3f,
	0x3d, 0x60, 0x13, 0xcc, 0x92, 0x02, 0x3f, 0xc2, 0x6f, 0x39, 0x1a, 0x62, 0x27, 0xf0, 0x28, 0x56,
	0xd9, 0x12, 0xb5, 0x11, 0x24, 0x55, 0x36, 0xdd, 0xb6, 0xa0, 0x5b, 0x0d, 0x9f, 0x27, 0xec, 0x0c,
	0x1e, 0x14, 0x50, 0xc6, 0x42, 0xfb, 0xa3, 0xe7, 0x7b, 0xdb, 0x8e, 0xb6, 0xa5, 0xfc, 0x02, 0x8e,
	0x6f, 0xa8, 0x30, 0x0b, 0x95, 0x19, 0x64, 0x6f, 0xa1, 0x8d, 0x1b, 0x43, 0x96, 0xdc, 0x1f, 0x9d,
	0xd4, 0x43, 0x5b, 0xff, 0x91, 0xab, 0xe2, 0x33, 0x60, 0x9f, 0x84, 0xa4, 0x43, 0xbd, 0xb9, 0xc4,
	0x99, 0xd4, 0xf3, 0x6d, 0xa2, 0xeb, 0x5e, 0xb7, 0x1a, 0x3e, 0x4f, 0x78, 0x0e, 0xc7, 0x37, 0x78,
	0x0a, 0xf5, 0x4f, 0xc1, 0x27, 0x39, 0x47, 0x95, 0xd3, 0xd4, 0x60, 0x5c, 0x90, 0x40, 0x11, 0x9a,
	0x60, 0x7c, 0x6d, 0xaf, 0x79, 0x90, 0xbd, 0xcf, 0x10, 0x8c, 0x53, 0x65, 0x70, 0x5c, 0x91, 0x7d,
	0x67, 0x93, 0x8f, 0xa1, 0x1d, 0x8b, 0xdc, 0x94, 0x8b, 0xe1, 0x2e, 0xfc, 0x12, 0x9e, 0xdc, 0x02,
	0xfd, 0x5f, 0xa6, 0x32, 0xfa, 0xdd, 0x82, 0xde, 0xfb, 0x54, 0xad, 0xc6, 0xf6, 0xa3, 0x9c, 0xb8,
	0x74, 0xf6, 0x03, 0xfc, 0xca, 0x06, 0xb0, 0x57, 0xf5, 0xa0, 0xbb, 0x6b, 0xdb, 0x3f, 0xbd, 0x63,
	0x95, 0x33, 0xc4, 0x1b, 0x1b, 0xf6, 0xca, 0x04, 0xf7, 0x61, 0xdf, 0x5d, 0xac, 0x7d, 0xd8, 0x6f,
	0x59, 0x13, 0xde, 0x60, 0xbf, 0x3c, 0xe8, 0xed, 0xb4, 0x9b, 0xbd, 0xae, 0x87, 0xfb, 0xd7, 0xf8,
	0xfb, 0x6f, 0x0e, 0xaa, 0x2d, 0x05, 0x5d, 0xdd, 0xb7, 0x7f, 0xca, 0x97, 0x7f, 0x03, 0x00, 0x00,
	0xff, 0xff, 0xda, 0x07, 0x33, 0x31, 0x3e, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FlowClientServiceClient is the client API for FlowClientService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FlowClientServiceClient interface {
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error)
	WaitMessage(ctx context.Context, in *WaitMessageRequest, opts ...grpc.CallOption) (*WaitMessageResponse, error)
	CloseConversation(ctx context.Context, in *CloseConversationRequest, opts ...grpc.CallOption) (*CloseConversationResponse, error)
}

type flowClientServiceClient struct {
	cc *grpc.ClientConn
}

func NewFlowClientServiceClient(cc *grpc.ClientConn) FlowClientServiceClient {
	return &flowClientServiceClient{cc}
}

func (c *flowClientServiceClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error) {
	out := new(SendMessageResponse)
	err := c.cc.Invoke(ctx, "/webitel.chat.service.flowadapter.FlowClientService/SendMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flowClientServiceClient) WaitMessage(ctx context.Context, in *WaitMessageRequest, opts ...grpc.CallOption) (*WaitMessageResponse, error) {
	out := new(WaitMessageResponse)
	err := c.cc.Invoke(ctx, "/webitel.chat.service.flowadapter.FlowClientService/WaitMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flowClientServiceClient) CloseConversation(ctx context.Context, in *CloseConversationRequest, opts ...grpc.CallOption) (*CloseConversationResponse, error) {
	out := new(CloseConversationResponse)
	err := c.cc.Invoke(ctx, "/webitel.chat.service.flowadapter.FlowClientService/CloseConversation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FlowClientServiceServer is the server API for FlowClientService service.
type FlowClientServiceServer interface {
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error)
	WaitMessage(context.Context, *WaitMessageRequest) (*WaitMessageResponse, error)
	CloseConversation(context.Context, *CloseConversationRequest) (*CloseConversationResponse, error)
}

// UnimplementedFlowClientServiceServer can be embedded to have forward compatible implementations.
type UnimplementedFlowClientServiceServer struct {
}

func (*UnimplementedFlowClientServiceServer) SendMessage(ctx context.Context, req *SendMessageRequest) (*SendMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (*UnimplementedFlowClientServiceServer) WaitMessage(ctx context.Context, req *WaitMessageRequest) (*WaitMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WaitMessage not implemented")
}
func (*UnimplementedFlowClientServiceServer) CloseConversation(ctx context.Context, req *CloseConversationRequest) (*CloseConversationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseConversation not implemented")
}

func RegisterFlowClientServiceServer(s *grpc.Server, srv FlowClientServiceServer) {
	s.RegisterService(&_FlowClientService_serviceDesc, srv)
}

func _FlowClientService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlowClientServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/webitel.chat.service.flowadapter.FlowClientService/SendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlowClientServiceServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlowClientService_WaitMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WaitMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlowClientServiceServer).WaitMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/webitel.chat.service.flowadapter.FlowClientService/WaitMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlowClientServiceServer).WaitMessage(ctx, req.(*WaitMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlowClientService_CloseConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseConversationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlowClientServiceServer).CloseConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/webitel.chat.service.flowadapter.FlowClientService/CloseConversation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlowClientServiceServer).CloseConversation(ctx, req.(*CloseConversationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FlowClientService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "webitel.chat.service.flowadapter.FlowClientService",
	HandlerType: (*FlowClientServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _FlowClientService_SendMessage_Handler,
		},
		{
			MethodName: "WaitMessage",
			Handler:    _FlowClientService_WaitMessage_Handler,
		},
		{
			MethodName: "CloseConversation",
			Handler:    _FlowClientService_CloseConversation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chat_client.proto",
}
