// Code generated by protoc-gen-go. DO NOT EDIT.
// source: connection.proto

package flow

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DistributeAttemptRequest struct {
	QueueId              int64             `protobuf:"varint,1,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"`
	MemberId             int64             `protobuf:"varint,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	AttemptId            int64             `protobuf:"varint,3,opt,name=attemptId,proto3" json:"attemptId,omitempty"`
	SchemaId             int64             `protobuf:"varint,4,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`
	SchemaVersion        int64             `protobuf:"varint,5,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Destination          string            `protobuf:"bytes,6,opt,name=destination,proto3" json:"destination,omitempty"`
	Variables            map[string]string `protobuf:"bytes,7,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DistributeAttemptRequest) Reset()         { *m = DistributeAttemptRequest{} }
func (m *DistributeAttemptRequest) String() string { return proto.CompactTextString(m) }
func (*DistributeAttemptRequest) ProtoMessage()    {}
func (*DistributeAttemptRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_51baa40a1cc6b48b, []int{0}
}

func (m *DistributeAttemptRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DistributeAttemptRequest.Unmarshal(m, b)
}
func (m *DistributeAttemptRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DistributeAttemptRequest.Marshal(b, m, deterministic)
}
func (m *DistributeAttemptRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DistributeAttemptRequest.Merge(m, src)
}
func (m *DistributeAttemptRequest) XXX_Size() int {
	return xxx_messageInfo_DistributeAttemptRequest.Size(m)
}
func (m *DistributeAttemptRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DistributeAttemptRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DistributeAttemptRequest proto.InternalMessageInfo

func (m *DistributeAttemptRequest) GetQueueId() int64 {
	if m != nil {
		return m.QueueId
	}
	return 0
}

func (m *DistributeAttemptRequest) GetMemberId() int64 {
	if m != nil {
		return m.MemberId
	}
	return 0
}

func (m *DistributeAttemptRequest) GetAttemptId() int64 {
	if m != nil {
		return m.AttemptId
	}
	return 0
}

func (m *DistributeAttemptRequest) GetSchemaId() int64 {
	if m != nil {
		return m.SchemaId
	}
	return 0
}

func (m *DistributeAttemptRequest) GetSchemaVersion() int64 {
	if m != nil {
		return m.SchemaVersion
	}
	return 0
}

func (m *DistributeAttemptRequest) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *DistributeAttemptRequest) GetVariables() map[string]string {
	if m != nil {
		return m.Variables
	}
	return nil
}

type DistributeAttemptResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DistributeAttemptResponse) Reset()         { *m = DistributeAttemptResponse{} }
func (m *DistributeAttemptResponse) String() string { return proto.CompactTextString(m) }
func (*DistributeAttemptResponse) ProtoMessage()    {}
func (*DistributeAttemptResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_51baa40a1cc6b48b, []int{1}
}

func (m *DistributeAttemptResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DistributeAttemptResponse.Unmarshal(m, b)
}
func (m *DistributeAttemptResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DistributeAttemptResponse.Marshal(b, m, deterministic)
}
func (m *DistributeAttemptResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DistributeAttemptResponse.Merge(m, src)
}
func (m *DistributeAttemptResponse) XXX_Size() int {
	return xxx_messageInfo_DistributeAttemptResponse.Size(m)
}
func (m *DistributeAttemptResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DistributeAttemptResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DistributeAttemptResponse proto.InternalMessageInfo

type DistributeAttemptResponse_Cancel struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DistributeAttemptResponse_Cancel) Reset()         { *m = DistributeAttemptResponse_Cancel{} }
func (m *DistributeAttemptResponse_Cancel) String() string { return proto.CompactTextString(m) }
func (*DistributeAttemptResponse_Cancel) ProtoMessage()    {}
func (*DistributeAttemptResponse_Cancel) Descriptor() ([]byte, []int) {
	return fileDescriptor_51baa40a1cc6b48b, []int{1, 0}
}

func (m *DistributeAttemptResponse_Cancel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DistributeAttemptResponse_Cancel.Unmarshal(m, b)
}
func (m *DistributeAttemptResponse_Cancel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DistributeAttemptResponse_Cancel.Marshal(b, m, deterministic)
}
func (m *DistributeAttemptResponse_Cancel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DistributeAttemptResponse_Cancel.Merge(m, src)
}
func (m *DistributeAttemptResponse_Cancel) XXX_Size() int {
	return xxx_messageInfo_DistributeAttemptResponse_Cancel.Size(m)
}
func (m *DistributeAttemptResponse_Cancel) XXX_DiscardUnknown() {
	xxx_messageInfo_DistributeAttemptResponse_Cancel.DiscardUnknown(m)
}

var xxx_messageInfo_DistributeAttemptResponse_Cancel proto.InternalMessageInfo

type DistributeAttemptResponse_Confirm struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DistributeAttemptResponse_Confirm) Reset()         { *m = DistributeAttemptResponse_Confirm{} }
func (m *DistributeAttemptResponse_Confirm) String() string { return proto.CompactTextString(m) }
func (*DistributeAttemptResponse_Confirm) ProtoMessage()    {}
func (*DistributeAttemptResponse_Confirm) Descriptor() ([]byte, []int) {
	return fileDescriptor_51baa40a1cc6b48b, []int{1, 1}
}

func (m *DistributeAttemptResponse_Confirm) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DistributeAttemptResponse_Confirm.Unmarshal(m, b)
}
func (m *DistributeAttemptResponse_Confirm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DistributeAttemptResponse_Confirm.Marshal(b, m, deterministic)
}
func (m *DistributeAttemptResponse_Confirm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DistributeAttemptResponse_Confirm.Merge(m, src)
}
func (m *DistributeAttemptResponse_Confirm) XXX_Size() int {
	return xxx_messageInfo_DistributeAttemptResponse_Confirm.Size(m)
}
func (m *DistributeAttemptResponse_Confirm) XXX_DiscardUnknown() {
	xxx_messageInfo_DistributeAttemptResponse_Confirm.DiscardUnknown(m)
}

var xxx_messageInfo_DistributeAttemptResponse_Confirm proto.InternalMessageInfo

func init() {
	proto.RegisterType((*DistributeAttemptRequest)(nil), "flow.DistributeAttemptRequest")
	proto.RegisterMapType((map[string]string)(nil), "flow.DistributeAttemptRequest.VariablesEntry")
	proto.RegisterType((*DistributeAttemptResponse)(nil), "flow.DistributeAttemptResponse")
	proto.RegisterType((*DistributeAttemptResponse_Cancel)(nil), "flow.DistributeAttemptResponse.Cancel")
	proto.RegisterType((*DistributeAttemptResponse_Confirm)(nil), "flow.DistributeAttemptResponse.Confirm")
}

func init() { proto.RegisterFile("connection.proto", fileDescriptor_51baa40a1cc6b48b) }

var fileDescriptor_51baa40a1cc6b48b = []byte{
	// 328 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0xc6, 0xdf, 0x34, 0xfd, 0x97, 0x29, 0x6f, 0xa9, 0x8b, 0x87, 0x34, 0x8a, 0x86, 0x82, 0xd0,
	0x8b, 0x41, 0xea, 0x45, 0xc4, 0x8b, 0x54, 0x85, 0xe0, 0x2d, 0x42, 0xaf, 0xb2, 0x49, 0xa6, 0xb8,
	0x98, 0xec, 0xb6, 0xbb, 0x9b, 0x94, 0x7e, 0x5c, 0xbf, 0x89, 0x64, 0x57, 0xa9, 0xa2, 0xf5, 0xb6,
	0xf3, 0xfc, 0xe6, 0x99, 0xe1, 0x19, 0x16, 0x46, 0x99, 0xe0, 0x1c, 0x33, 0xcd, 0x04, 0x8f, 0x56,
	0x52, 0x68, 0x41, 0xda, 0xcb, 0x42, 0x6c, 0x26, 0x6f, 0x2d, 0xf0, 0xef, 0x98, 0xd2, 0x92, 0xa5,
	0x95, 0xc6, 0x5b, 0xad, 0xb1, 0x5c, 0xe9, 0x04, 0xd7, 0x15, 0x2a, 0x4d, 0xc6, 0xd0, 0x5f, 0x57,
	0x58, 0xe1, 0x33, 0xcb, 0x7d, 0x27, 0x74, 0xa6, 0x6e, 0xd2, 0x33, 0x75, 0x9c, 0x93, 0x23, 0xf0,
	0x4a, 0x2c, 0x53, 0x94, 0x0d, 0x6b, 0x19, 0xd6, 0xb7, 0x42, 0x9c, 0x93, 0x63, 0xf0, 0xa8, 0x9d,
	0x14, 0xe7, 0xbe, 0x6b, 0xe0, 0x4e, 0x68, 0xac, 0x2a, 0x7b, 0xc1, 0x92, 0x36, 0xd6, 0xb6, 0xb5,
	0x5a, 0x21, 0xce, 0xc9, 0x19, 0x0c, 0x3f, 0x60, 0x8d, 0x52, 0x31, 0xc1, 0xfd, 0x8e, 0xe9, 0xf8,
	0x6f, 0xd5, 0x85, 0x15, 0x49, 0x08, 0x83, 0x1c, 0x95, 0x66, 0x9c, 0x36, 0x89, 0xfc, 0x6e, 0xe8,
	0x4c, 0xbd, 0xe4, 0xab, 0x44, 0x1e, 0xc1, 0xab, 0xa9, 0x64, 0x34, 0x2d, 0x50, 0xf9, 0xbd, 0xd0,
	0x9d, 0x0e, 0x66, 0xe7, 0x51, 0x13, 0x39, 0xda, 0x17, 0x37, 0x5a, 0x7c, 0xf6, 0xdf, 0x73, 0x2d,
	0xb7, 0xc9, 0xce, 0x1f, 0xdc, 0xc0, 0xf0, 0x3b, 0x24, 0x23, 0x70, 0x5f, 0x71, 0x6b, 0xae, 0xe2,
	0x25, 0xcd, 0x93, 0x1c, 0x42, 0xa7, 0xa6, 0x45, 0x85, 0xe6, 0x1a, 0x5e, 0x62, 0x8b, 0xeb, 0xd6,
	0x95, 0x33, 0xb9, 0x80, 0xf1, 0x2f, 0x3b, 0xd5, 0x4a, 0x70, 0x85, 0x41, 0x1f, 0xba, 0x73, 0xca,
	0x33, 0x2c, 0x02, 0x0f, 0x7a, 0x73, 0xc1, 0x97, 0x4c, 0x96, 0x33, 0x84, 0xc1, 0x43, 0x21, 0x36,
	0x4f, 0x28, 0x6b, 0x96, 0x21, 0x59, 0xc0, 0xc1, 0x8f, 0x01, 0xe4, 0xe4, 0xef, 0x34, 0xc1, 0xe9,
	0x5e, 0x6e, 0x37, 0x4f, 0xfe, 0xa5, 0x5d, 0xf3, 0x13, 0x2e, 0xdf, 0x03, 0x00, 0x00, 0xff, 0xff,
	0x6e, 0x88, 0xee, 0x81, 0x1d, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FlowServiceClient is the client API for FlowService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FlowServiceClient interface {
	DistributeAttempt(ctx context.Context, in *DistributeAttemptRequest, opts ...grpc.CallOption) (*DistributeAttemptResponse, error)
}

type flowServiceClient struct {
	cc *grpc.ClientConn
}

func NewFlowServiceClient(cc *grpc.ClientConn) FlowServiceClient {
	return &flowServiceClient{cc}
}

func (c *flowServiceClient) DistributeAttempt(ctx context.Context, in *DistributeAttemptRequest, opts ...grpc.CallOption) (*DistributeAttemptResponse, error) {
	out := new(DistributeAttemptResponse)
	err := c.cc.Invoke(ctx, "/flow.FlowService/DistributeAttempt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FlowServiceServer is the server API for FlowService service.
type FlowServiceServer interface {
	DistributeAttempt(context.Context, *DistributeAttemptRequest) (*DistributeAttemptResponse, error)
}

// UnimplementedFlowServiceServer can be embedded to have forward compatible implementations.
type UnimplementedFlowServiceServer struct {
}

func (*UnimplementedFlowServiceServer) DistributeAttempt(ctx context.Context, req *DistributeAttemptRequest) (*DistributeAttemptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DistributeAttempt not implemented")
}

func RegisterFlowServiceServer(s *grpc.Server, srv FlowServiceServer) {
	s.RegisterService(&_FlowService_serviceDesc, srv)
}

func _FlowService_DistributeAttempt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DistributeAttemptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlowServiceServer).DistributeAttempt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flow.FlowService/DistributeAttempt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlowServiceServer).DistributeAttempt(ctx, req.(*DistributeAttemptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FlowService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "flow.FlowService",
	HandlerType: (*FlowServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DistributeAttempt",
			Handler:    _FlowService_DistributeAttempt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "connection.proto",
}
