// Code generated by protoc-gen-go. DO NOT EDIT.
// source: connection.proto

package flow

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DistributeAttemptRequest struct {
	SchemaId             int32             `protobuf:"varint,1,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`
	DomainId             int64             `protobuf:"varint,2,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	Destination          string            `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	Display              string            `protobuf:"bytes,4,opt,name=display,proto3" json:"display,omitempty"`
	Variables            map[string]string `protobuf:"bytes,5,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DistributeAttemptRequest) Reset()         { *m = DistributeAttemptRequest{} }
func (m *DistributeAttemptRequest) String() string { return proto.CompactTextString(m) }
func (*DistributeAttemptRequest) ProtoMessage()    {}
func (*DistributeAttemptRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_51baa40a1cc6b48b, []int{0}
}

func (m *DistributeAttemptRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DistributeAttemptRequest.Unmarshal(m, b)
}
func (m *DistributeAttemptRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DistributeAttemptRequest.Marshal(b, m, deterministic)
}
func (m *DistributeAttemptRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DistributeAttemptRequest.Merge(m, src)
}
func (m *DistributeAttemptRequest) XXX_Size() int {
	return xxx_messageInfo_DistributeAttemptRequest.Size(m)
}
func (m *DistributeAttemptRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DistributeAttemptRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DistributeAttemptRequest proto.InternalMessageInfo

func (m *DistributeAttemptRequest) GetSchemaId() int32 {
	if m != nil {
		return m.SchemaId
	}
	return 0
}

func (m *DistributeAttemptRequest) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

func (m *DistributeAttemptRequest) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *DistributeAttemptRequest) GetDisplay() string {
	if m != nil {
		return m.Display
	}
	return ""
}

func (m *DistributeAttemptRequest) GetVariables() map[string]string {
	if m != nil {
		return m.Variables
	}
	return nil
}

type DistributeAttemptResponse struct {
	// Types that are valid to be assigned to Result:
	//	*DistributeAttemptResponse_Cancel_
	//	*DistributeAttemptResponse_Confirm_
	Result               isDistributeAttemptResponse_Result `protobuf_oneof:"result"`
	Variables            map[string]string                  `protobuf:"bytes,3,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *DistributeAttemptResponse) Reset()         { *m = DistributeAttemptResponse{} }
func (m *DistributeAttemptResponse) String() string { return proto.CompactTextString(m) }
func (*DistributeAttemptResponse) ProtoMessage()    {}
func (*DistributeAttemptResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_51baa40a1cc6b48b, []int{1}
}

func (m *DistributeAttemptResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DistributeAttemptResponse.Unmarshal(m, b)
}
func (m *DistributeAttemptResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DistributeAttemptResponse.Marshal(b, m, deterministic)
}
func (m *DistributeAttemptResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DistributeAttemptResponse.Merge(m, src)
}
func (m *DistributeAttemptResponse) XXX_Size() int {
	return xxx_messageInfo_DistributeAttemptResponse.Size(m)
}
func (m *DistributeAttemptResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DistributeAttemptResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DistributeAttemptResponse proto.InternalMessageInfo

type isDistributeAttemptResponse_Result interface {
	isDistributeAttemptResponse_Result()
}

type DistributeAttemptResponse_Cancel_ struct {
	Cancel *DistributeAttemptResponse_Cancel `protobuf:"bytes,1,opt,name=cancel,proto3,oneof"`
}

type DistributeAttemptResponse_Confirm_ struct {
	Confirm *DistributeAttemptResponse_Confirm `protobuf:"bytes,2,opt,name=confirm,proto3,oneof"`
}

func (*DistributeAttemptResponse_Cancel_) isDistributeAttemptResponse_Result() {}

func (*DistributeAttemptResponse_Confirm_) isDistributeAttemptResponse_Result() {}

func (m *DistributeAttemptResponse) GetResult() isDistributeAttemptResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *DistributeAttemptResponse) GetCancel() *DistributeAttemptResponse_Cancel {
	if x, ok := m.GetResult().(*DistributeAttemptResponse_Cancel_); ok {
		return x.Cancel
	}
	return nil
}

func (m *DistributeAttemptResponse) GetConfirm() *DistributeAttemptResponse_Confirm {
	if x, ok := m.GetResult().(*DistributeAttemptResponse_Confirm_); ok {
		return x.Confirm
	}
	return nil
}

func (m *DistributeAttemptResponse) GetVariables() map[string]string {
	if m != nil {
		return m.Variables
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*DistributeAttemptResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*DistributeAttemptResponse_Cancel_)(nil),
		(*DistributeAttemptResponse_Confirm_)(nil),
	}
}

type DistributeAttemptResponse_Cancel struct {
	Description          string   `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	NextDistributeSec    uint32   `protobuf:"varint,2,opt,name=next_distribute_sec,json=nextDistributeSec,proto3" json:"next_distribute_sec,omitempty"`
	Stop                 bool     `protobuf:"varint,3,opt,name=stop,proto3" json:"stop,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DistributeAttemptResponse_Cancel) Reset()         { *m = DistributeAttemptResponse_Cancel{} }
func (m *DistributeAttemptResponse_Cancel) String() string { return proto.CompactTextString(m) }
func (*DistributeAttemptResponse_Cancel) ProtoMessage()    {}
func (*DistributeAttemptResponse_Cancel) Descriptor() ([]byte, []int) {
	return fileDescriptor_51baa40a1cc6b48b, []int{1, 0}
}

func (m *DistributeAttemptResponse_Cancel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DistributeAttemptResponse_Cancel.Unmarshal(m, b)
}
func (m *DistributeAttemptResponse_Cancel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DistributeAttemptResponse_Cancel.Marshal(b, m, deterministic)
}
func (m *DistributeAttemptResponse_Cancel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DistributeAttemptResponse_Cancel.Merge(m, src)
}
func (m *DistributeAttemptResponse_Cancel) XXX_Size() int {
	return xxx_messageInfo_DistributeAttemptResponse_Cancel.Size(m)
}
func (m *DistributeAttemptResponse_Cancel) XXX_DiscardUnknown() {
	xxx_messageInfo_DistributeAttemptResponse_Cancel.DiscardUnknown(m)
}

var xxx_messageInfo_DistributeAttemptResponse_Cancel proto.InternalMessageInfo

func (m *DistributeAttemptResponse_Cancel) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *DistributeAttemptResponse_Cancel) GetNextDistributeSec() uint32 {
	if m != nil {
		return m.NextDistributeSec
	}
	return 0
}

func (m *DistributeAttemptResponse_Cancel) GetStop() bool {
	if m != nil {
		return m.Stop
	}
	return false
}

type DistributeAttemptResponse_Confirm struct {
	Destination          string   `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"`
	Display              string   `protobuf:"bytes,2,opt,name=display,proto3" json:"display,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DistributeAttemptResponse_Confirm) Reset()         { *m = DistributeAttemptResponse_Confirm{} }
func (m *DistributeAttemptResponse_Confirm) String() string { return proto.CompactTextString(m) }
func (*DistributeAttemptResponse_Confirm) ProtoMessage()    {}
func (*DistributeAttemptResponse_Confirm) Descriptor() ([]byte, []int) {
	return fileDescriptor_51baa40a1cc6b48b, []int{1, 1}
}

func (m *DistributeAttemptResponse_Confirm) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DistributeAttemptResponse_Confirm.Unmarshal(m, b)
}
func (m *DistributeAttemptResponse_Confirm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DistributeAttemptResponse_Confirm.Marshal(b, m, deterministic)
}
func (m *DistributeAttemptResponse_Confirm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DistributeAttemptResponse_Confirm.Merge(m, src)
}
func (m *DistributeAttemptResponse_Confirm) XXX_Size() int {
	return xxx_messageInfo_DistributeAttemptResponse_Confirm.Size(m)
}
func (m *DistributeAttemptResponse_Confirm) XXX_DiscardUnknown() {
	xxx_messageInfo_DistributeAttemptResponse_Confirm.DiscardUnknown(m)
}

var xxx_messageInfo_DistributeAttemptResponse_Confirm proto.InternalMessageInfo

func (m *DistributeAttemptResponse_Confirm) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *DistributeAttemptResponse_Confirm) GetDisplay() string {
	if m != nil {
		return m.Display
	}
	return ""
}

func init() {
	proto.RegisterType((*DistributeAttemptRequest)(nil), "flow.DistributeAttemptRequest")
	proto.RegisterMapType((map[string]string)(nil), "flow.DistributeAttemptRequest.VariablesEntry")
	proto.RegisterType((*DistributeAttemptResponse)(nil), "flow.DistributeAttemptResponse")
	proto.RegisterMapType((map[string]string)(nil), "flow.DistributeAttemptResponse.VariablesEntry")
	proto.RegisterType((*DistributeAttemptResponse_Cancel)(nil), "flow.DistributeAttemptResponse.Cancel")
	proto.RegisterType((*DistributeAttemptResponse_Confirm)(nil), "flow.DistributeAttemptResponse.Confirm")
}

func init() { proto.RegisterFile("connection.proto", fileDescriptor_51baa40a1cc6b48b) }

var fileDescriptor_51baa40a1cc6b48b = []byte{
	// 424 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x8d, 0xe3, 0xc4, 0xb1, 0xc7, 0x02, 0xb5, 0x0b, 0x07, 0x13, 0x24, 0xb0, 0x72, 0x00, 0x5f,
	0xf0, 0xc1, 0x5c, 0x10, 0xe2, 0x00, 0x94, 0xa2, 0x56, 0x70, 0xda, 0x4a, 0xbd, 0x46, 0x9b, 0xf5,
	0x54, 0xac, 0xb0, 0x77, 0xcd, 0xee, 0x3a, 0x25, 0xbf, 0x85, 0x1f, 0xc9, 0x5f, 0x40, 0x5e, 0xc7,
	0xfd, 0x00, 0xd2, 0x1c, 0x7a, 0xf3, 0xce, 0x9b, 0x8f, 0x37, 0x6f, 0x9e, 0xe1, 0x80, 0x2b, 0x29,
	0x91, 0x5b, 0xa1, 0x64, 0xde, 0x68, 0x65, 0x15, 0x99, 0x5c, 0x54, 0xea, 0x72, 0xf1, 0x6b, 0x0c,
	0xc9, 0x27, 0x61, 0xac, 0x16, 0xab, 0xd6, 0xe2, 0x07, 0x6b, 0xb1, 0x6e, 0x2c, 0xc5, 0x1f, 0x2d,
	0x1a, 0x4b, 0x9e, 0x42, 0x64, 0xf8, 0x37, 0xac, 0xd9, 0x52, 0x94, 0x89, 0x97, 0x7a, 0xd9, 0x94,
	0x86, 0x7d, 0xe0, 0xb4, 0xec, 0xc0, 0x52, 0xd5, 0x4c, 0xc8, 0x0e, 0x1c, 0xa7, 0x5e, 0xe6, 0xd3,
	0xb0, 0x0f, 0x9c, 0x96, 0x24, 0x85, 0xb8, 0x44, 0x63, 0x85, 0x64, 0xdd, 0xc4, 0xc4, 0x4f, 0xbd,
	0x2c, 0xa2, 0x37, 0x43, 0x24, 0x81, 0x59, 0x29, 0x4c, 0x53, 0xb1, 0x4d, 0x32, 0x71, 0xe8, 0xf0,
	0x24, 0x5f, 0x20, 0x5a, 0x33, 0x2d, 0xd8, 0xaa, 0x42, 0x93, 0x4c, 0x53, 0x3f, 0x8b, 0x8b, 0x57,
	0x79, 0x47, 0x36, 0xdf, 0x45, 0x34, 0x3f, 0x1f, 0xf2, 0x8f, 0xa5, 0xd5, 0x1b, 0x7a, 0x5d, 0x3f,
	0x7f, 0x07, 0x0f, 0x6f, 0x83, 0xe4, 0x00, 0xfc, 0xef, 0xb8, 0x71, 0xeb, 0x44, 0xb4, 0xfb, 0x24,
	0x8f, 0x61, 0xba, 0x66, 0x55, 0x8b, 0x6e, 0x8b, 0x88, 0xf6, 0x8f, 0xb7, 0xe3, 0x37, 0xde, 0xe2,
	0xb7, 0x0f, 0x4f, 0xfe, 0x33, 0xd4, 0x34, 0x4a, 0x1a, 0x24, 0xef, 0x21, 0xe0, 0x4c, 0x72, 0xac,
	0x5c, 0xb3, 0xb8, 0x78, 0xb1, 0x93, 0x65, 0x5f, 0x90, 0x1f, 0xb9, 0xec, 0x93, 0x11, 0xdd, 0xd6,
	0x91, 0x23, 0x98, 0x71, 0x25, 0x2f, 0x84, 0xae, 0xdd, 0xec, 0xb8, 0x78, 0xb9, 0xb7, 0x45, 0x9f,
	0x7e, 0x32, 0xa2, 0x43, 0x25, 0xf9, 0x7a, 0x53, 0x2f, 0xdf, 0xe9, 0x95, 0xef, 0x6b, 0xb3, 0x5b,
	0x30, 0x09, 0x41, 0x4f, 0x73, 0x7b, 0x43, 0xae, 0x45, 0xe3, 0x6e, 0xe8, 0x5d, 0xdd, 0x70, 0x08,
	0x91, 0x1c, 0x1e, 0x49, 0xfc, 0x69, 0x97, 0xe5, 0xd5, 0x9c, 0xa5, 0x41, 0xee, 0x56, 0x79, 0x40,
	0x0f, 0x3b, 0xe8, 0x9a, 0xc1, 0x19, 0x72, 0x42, 0x60, 0x62, 0xac, 0x6a, 0x9c, 0x1d, 0x42, 0xea,
	0xbe, 0xe7, 0xc7, 0x30, 0xdb, 0xee, 0xf4, 0xb7, 0x69, 0xbc, 0x3b, 0x4d, 0x33, 0xbe, 0x65, 0x9a,
	0xfb, 0xdd, 0xf9, 0x63, 0x08, 0x81, 0x46, 0xd3, 0x56, 0xb6, 0x40, 0x88, 0x3f, 0x57, 0xea, 0xf2,
	0x0c, 0xf5, 0x5a, 0x70, 0x24, 0xe7, 0x70, 0xf8, 0x8f, 0x88, 0xe4, 0xd9, 0xdd, 0x6e, 0x9c, 0x3f,
	0xdf, 0xa3, 0xfe, 0x62, 0xb4, 0x0a, 0xdc, 0x3f, 0xf8, 0xfa, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x29, 0x58, 0x4e, 0x5e, 0x97, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FlowServiceClient is the client API for FlowService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FlowServiceClient interface {
	DistributeAttempt(ctx context.Context, in *DistributeAttemptRequest, opts ...grpc.CallOption) (*DistributeAttemptResponse, error)
}

type flowServiceClient struct {
	cc *grpc.ClientConn
}

func NewFlowServiceClient(cc *grpc.ClientConn) FlowServiceClient {
	return &flowServiceClient{cc}
}

func (c *flowServiceClient) DistributeAttempt(ctx context.Context, in *DistributeAttemptRequest, opts ...grpc.CallOption) (*DistributeAttemptResponse, error) {
	out := new(DistributeAttemptResponse)
	err := c.cc.Invoke(ctx, "/flow.FlowService/DistributeAttempt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FlowServiceServer is the server API for FlowService service.
type FlowServiceServer interface {
	DistributeAttempt(context.Context, *DistributeAttemptRequest) (*DistributeAttemptResponse, error)
}

// UnimplementedFlowServiceServer can be embedded to have forward compatible implementations.
type UnimplementedFlowServiceServer struct {
}

func (*UnimplementedFlowServiceServer) DistributeAttempt(ctx context.Context, req *DistributeAttemptRequest) (*DistributeAttemptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DistributeAttempt not implemented")
}

func RegisterFlowServiceServer(s *grpc.Server, srv FlowServiceServer) {
	s.RegisterService(&_FlowService_serviceDesc, srv)
}

func _FlowService_DistributeAttempt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DistributeAttemptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlowServiceServer).DistributeAttempt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flow.FlowService/DistributeAttempt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlowServiceServer).DistributeAttempt(ctx, req.(*DistributeAttemptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FlowService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "flow.FlowService",
	HandlerType: (*FlowServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DistributeAttempt",
			Handler:    _FlowService_DistributeAttempt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "connection.proto",
}
