// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fs.proto

package fs

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ErrorExecute_Type int32

const (
	ErrorExecute_ERROR ErrorExecute_Type = 0
	ErrorExecute_USAGE ErrorExecute_Type = 1
)

var ErrorExecute_Type_name = map[int32]string{
	0: "ERROR",
	1: "USAGE",
}

var ErrorExecute_Type_value = map[string]int32{
	"ERROR": 0,
	"USAGE": 1,
}

func (x ErrorExecute_Type) String() string {
	return proto.EnumName(ErrorExecute_Type_name, int32(x))
}

func (ErrorExecute_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e604833c2b457e38, []int{4, 0}
}

type OriginateRequest_Strategy int32

const (
	OriginateRequest_FAILOVER OriginateRequest_Strategy = 0
	OriginateRequest_MULTIPLE OriginateRequest_Strategy = 1
)

var OriginateRequest_Strategy_name = map[int32]string{
	0: "FAILOVER",
	1: "MULTIPLE",
}

var OriginateRequest_Strategy_value = map[string]int32{
	"FAILOVER": 0,
	"MULTIPLE": 1,
}

func (x OriginateRequest_Strategy) String() string {
	return proto.EnumName(OriginateRequest_Strategy_name, int32(x))
}

func (OriginateRequest_Strategy) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e604833c2b457e38, []int{9, 0}
}

type VoiceStreamRequest struct {
	// Types that are valid to be assigned to Data:
	//	*VoiceStreamRequest_Request
	//	*VoiceStreamRequest_Chunk_
	Data                 isVoiceStreamRequest_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *VoiceStreamRequest) Reset()         { *m = VoiceStreamRequest{} }
func (m *VoiceStreamRequest) String() string { return proto.CompactTextString(m) }
func (*VoiceStreamRequest) ProtoMessage()    {}
func (*VoiceStreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e604833c2b457e38, []int{0}
}

func (m *VoiceStreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoiceStreamRequest.Unmarshal(m, b)
}
func (m *VoiceStreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoiceStreamRequest.Marshal(b, m, deterministic)
}
func (m *VoiceStreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoiceStreamRequest.Merge(m, src)
}
func (m *VoiceStreamRequest) XXX_Size() int {
	return xxx_messageInfo_VoiceStreamRequest.Size(m)
}
func (m *VoiceStreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VoiceStreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VoiceStreamRequest proto.InternalMessageInfo

type isVoiceStreamRequest_Data interface {
	isVoiceStreamRequest_Data()
}

type VoiceStreamRequest_Request struct {
	Request *VoiceStreamRequest_Init `protobuf:"bytes,1,opt,name=request,proto3,oneof"`
}

type VoiceStreamRequest_Chunk_ struct {
	Chunk *VoiceStreamRequest_Chunk `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*VoiceStreamRequest_Request) isVoiceStreamRequest_Data() {}

func (*VoiceStreamRequest_Chunk_) isVoiceStreamRequest_Data() {}

func (m *VoiceStreamRequest) GetData() isVoiceStreamRequest_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *VoiceStreamRequest) GetRequest() *VoiceStreamRequest_Init {
	if x, ok := m.GetData().(*VoiceStreamRequest_Request); ok {
		return x.Request
	}
	return nil
}

func (m *VoiceStreamRequest) GetChunk() *VoiceStreamRequest_Chunk {
	if x, ok := m.GetData().(*VoiceStreamRequest_Chunk_); ok {
		return x.Chunk
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*VoiceStreamRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*VoiceStreamRequest_Request)(nil),
		(*VoiceStreamRequest_Chunk_)(nil),
	}
}

type VoiceStreamRequest_Init struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VoiceStreamRequest_Init) Reset()         { *m = VoiceStreamRequest_Init{} }
func (m *VoiceStreamRequest_Init) String() string { return proto.CompactTextString(m) }
func (*VoiceStreamRequest_Init) ProtoMessage()    {}
func (*VoiceStreamRequest_Init) Descriptor() ([]byte, []int) {
	return fileDescriptor_e604833c2b457e38, []int{0, 0}
}

func (m *VoiceStreamRequest_Init) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoiceStreamRequest_Init.Unmarshal(m, b)
}
func (m *VoiceStreamRequest_Init) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoiceStreamRequest_Init.Marshal(b, m, deterministic)
}
func (m *VoiceStreamRequest_Init) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoiceStreamRequest_Init.Merge(m, src)
}
func (m *VoiceStreamRequest_Init) XXX_Size() int {
	return xxx_messageInfo_VoiceStreamRequest_Init.Size(m)
}
func (m *VoiceStreamRequest_Init) XXX_DiscardUnknown() {
	xxx_messageInfo_VoiceStreamRequest_Init.DiscardUnknown(m)
}

var xxx_messageInfo_VoiceStreamRequest_Init proto.InternalMessageInfo

func (m *VoiceStreamRequest_Init) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type VoiceStreamRequest_Chunk struct {
	Content              []byte   `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VoiceStreamRequest_Chunk) Reset()         { *m = VoiceStreamRequest_Chunk{} }
func (m *VoiceStreamRequest_Chunk) String() string { return proto.CompactTextString(m) }
func (*VoiceStreamRequest_Chunk) ProtoMessage()    {}
func (*VoiceStreamRequest_Chunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_e604833c2b457e38, []int{0, 1}
}

func (m *VoiceStreamRequest_Chunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoiceStreamRequest_Chunk.Unmarshal(m, b)
}
func (m *VoiceStreamRequest_Chunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoiceStreamRequest_Chunk.Marshal(b, m, deterministic)
}
func (m *VoiceStreamRequest_Chunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoiceStreamRequest_Chunk.Merge(m, src)
}
func (m *VoiceStreamRequest_Chunk) XXX_Size() int {
	return xxx_messageInfo_VoiceStreamRequest_Chunk.Size(m)
}
func (m *VoiceStreamRequest_Chunk) XXX_DiscardUnknown() {
	xxx_messageInfo_VoiceStreamRequest_Chunk.DiscardUnknown(m)
}

var xxx_messageInfo_VoiceStreamRequest_Chunk proto.InternalMessageInfo

func (m *VoiceStreamRequest_Chunk) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type VoiceStreamResponse struct {
	// Types that are valid to be assigned to Data:
	//	*VoiceStreamResponse_Chunk_
	Data                 isVoiceStreamResponse_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *VoiceStreamResponse) Reset()         { *m = VoiceStreamResponse{} }
func (m *VoiceStreamResponse) String() string { return proto.CompactTextString(m) }
func (*VoiceStreamResponse) ProtoMessage()    {}
func (*VoiceStreamResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e604833c2b457e38, []int{1}
}

func (m *VoiceStreamResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoiceStreamResponse.Unmarshal(m, b)
}
func (m *VoiceStreamResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoiceStreamResponse.Marshal(b, m, deterministic)
}
func (m *VoiceStreamResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoiceStreamResponse.Merge(m, src)
}
func (m *VoiceStreamResponse) XXX_Size() int {
	return xxx_messageInfo_VoiceStreamResponse.Size(m)
}
func (m *VoiceStreamResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VoiceStreamResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VoiceStreamResponse proto.InternalMessageInfo

type isVoiceStreamResponse_Data interface {
	isVoiceStreamResponse_Data()
}

type VoiceStreamResponse_Chunk_ struct {
	Chunk *VoiceStreamResponse_Chunk `protobuf:"bytes,1,opt,name=chunk,proto3,oneof"`
}

func (*VoiceStreamResponse_Chunk_) isVoiceStreamResponse_Data() {}

func (m *VoiceStreamResponse) GetData() isVoiceStreamResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *VoiceStreamResponse) GetChunk() *VoiceStreamResponse_Chunk {
	if x, ok := m.GetData().(*VoiceStreamResponse_Chunk_); ok {
		return x.Chunk
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*VoiceStreamResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*VoiceStreamResponse_Chunk_)(nil),
	}
}

type VoiceStreamResponse_Chunk struct {
	Content              []byte   `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VoiceStreamResponse_Chunk) Reset()         { *m = VoiceStreamResponse_Chunk{} }
func (m *VoiceStreamResponse_Chunk) String() string { return proto.CompactTextString(m) }
func (*VoiceStreamResponse_Chunk) ProtoMessage()    {}
func (*VoiceStreamResponse_Chunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_e604833c2b457e38, []int{1, 0}
}

func (m *VoiceStreamResponse_Chunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoiceStreamResponse_Chunk.Unmarshal(m, b)
}
func (m *VoiceStreamResponse_Chunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoiceStreamResponse_Chunk.Marshal(b, m, deterministic)
}
func (m *VoiceStreamResponse_Chunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoiceStreamResponse_Chunk.Merge(m, src)
}
func (m *VoiceStreamResponse_Chunk) XXX_Size() int {
	return xxx_messageInfo_VoiceStreamResponse_Chunk.Size(m)
}
func (m *VoiceStreamResponse_Chunk) XXX_DiscardUnknown() {
	xxx_messageInfo_VoiceStreamResponse_Chunk.DiscardUnknown(m)
}

var xxx_messageInfo_VoiceStreamResponse_Chunk proto.InternalMessageInfo

func (m *VoiceStreamResponse_Chunk) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type QueueRequest struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Variables            map[string]string `protobuf:"bytes,2,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	PlaybackFile         string            `protobuf:"bytes,3,opt,name=playback_file,json=playbackFile,proto3" json:"playback_file,omitempty"`
	PlaybackArgs         int32             `protobuf:"varint,4,opt,name=playback_args,json=playbackArgs,proto3" json:"playback_args,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *QueueRequest) Reset()         { *m = QueueRequest{} }
func (m *QueueRequest) String() string { return proto.CompactTextString(m) }
func (*QueueRequest) ProtoMessage()    {}
func (*QueueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e604833c2b457e38, []int{2}
}

func (m *QueueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueRequest.Unmarshal(m, b)
}
func (m *QueueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueRequest.Marshal(b, m, deterministic)
}
func (m *QueueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueRequest.Merge(m, src)
}
func (m *QueueRequest) XXX_Size() int {
	return xxx_messageInfo_QueueRequest.Size(m)
}
func (m *QueueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueueRequest proto.InternalMessageInfo

func (m *QueueRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *QueueRequest) GetVariables() map[string]string {
	if m != nil {
		return m.Variables
	}
	return nil
}

func (m *QueueRequest) GetPlaybackFile() string {
	if m != nil {
		return m.PlaybackFile
	}
	return ""
}

func (m *QueueRequest) GetPlaybackArgs() int32 {
	if m != nil {
		return m.PlaybackArgs
	}
	return 0
}

type QueueResponse struct {
	Error                *ErrorExecute `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *QueueResponse) Reset()         { *m = QueueResponse{} }
func (m *QueueResponse) String() string { return proto.CompactTextString(m) }
func (*QueueResponse) ProtoMessage()    {}
func (*QueueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e604833c2b457e38, []int{3}
}

func (m *QueueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueResponse.Unmarshal(m, b)
}
func (m *QueueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueResponse.Marshal(b, m, deterministic)
}
func (m *QueueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueResponse.Merge(m, src)
}
func (m *QueueResponse) XXX_Size() int {
	return xxx_messageInfo_QueueResponse.Size(m)
}
func (m *QueueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueueResponse proto.InternalMessageInfo

func (m *QueueResponse) GetError() *ErrorExecute {
	if m != nil {
		return m.Error
	}
	return nil
}

type ErrorExecute struct {
	Message              string            `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Type                 ErrorExecute_Type `protobuf:"varint,2,opt,name=type,proto3,enum=fs.ErrorExecute_Type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ErrorExecute) Reset()         { *m = ErrorExecute{} }
func (m *ErrorExecute) String() string { return proto.CompactTextString(m) }
func (*ErrorExecute) ProtoMessage()    {}
func (*ErrorExecute) Descriptor() ([]byte, []int) {
	return fileDescriptor_e604833c2b457e38, []int{4}
}

func (m *ErrorExecute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorExecute.Unmarshal(m, b)
}
func (m *ErrorExecute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorExecute.Marshal(b, m, deterministic)
}
func (m *ErrorExecute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorExecute.Merge(m, src)
}
func (m *ErrorExecute) XXX_Size() int {
	return xxx_messageInfo_ErrorExecute.Size(m)
}
func (m *ErrorExecute) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorExecute.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorExecute proto.InternalMessageInfo

func (m *ErrorExecute) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ErrorExecute) GetType() ErrorExecute_Type {
	if m != nil {
		return m.Type
	}
	return ErrorExecute_ERROR
}

type ExecuteRequest struct {
	Command              string   `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Args                 string   `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecuteRequest) Reset()         { *m = ExecuteRequest{} }
func (m *ExecuteRequest) String() string { return proto.CompactTextString(m) }
func (*ExecuteRequest) ProtoMessage()    {}
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e604833c2b457e38, []int{5}
}

func (m *ExecuteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteRequest.Unmarshal(m, b)
}
func (m *ExecuteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteRequest.Marshal(b, m, deterministic)
}
func (m *ExecuteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteRequest.Merge(m, src)
}
func (m *ExecuteRequest) XXX_Size() int {
	return xxx_messageInfo_ExecuteRequest.Size(m)
}
func (m *ExecuteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteRequest proto.InternalMessageInfo

func (m *ExecuteRequest) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *ExecuteRequest) GetArgs() string {
	if m != nil {
		return m.Args
	}
	return ""
}

type ExecuteResponse struct {
	Data                 string        `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error                *ErrorExecute `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ExecuteResponse) Reset()         { *m = ExecuteResponse{} }
func (m *ExecuteResponse) String() string { return proto.CompactTextString(m) }
func (*ExecuteResponse) ProtoMessage()    {}
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e604833c2b457e38, []int{6}
}

func (m *ExecuteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteResponse.Unmarshal(m, b)
}
func (m *ExecuteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteResponse.Marshal(b, m, deterministic)
}
func (m *ExecuteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteResponse.Merge(m, src)
}
func (m *ExecuteResponse) XXX_Size() int {
	return xxx_messageInfo_ExecuteResponse.Size(m)
}
func (m *ExecuteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteResponse proto.InternalMessageInfo

func (m *ExecuteResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *ExecuteResponse) GetError() *ErrorExecute {
	if m != nil {
		return m.Error
	}
	return nil
}

type HangupRequest struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Cause                string   `protobuf:"bytes,2,opt,name=cause,proto3" json:"cause,omitempty"`
	Reporting            bool     `protobuf:"varint,3,opt,name=reporting,proto3" json:"reporting,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HangupRequest) Reset()         { *m = HangupRequest{} }
func (m *HangupRequest) String() string { return proto.CompactTextString(m) }
func (*HangupRequest) ProtoMessage()    {}
func (*HangupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e604833c2b457e38, []int{7}
}

func (m *HangupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HangupRequest.Unmarshal(m, b)
}
func (m *HangupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HangupRequest.Marshal(b, m, deterministic)
}
func (m *HangupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HangupRequest.Merge(m, src)
}
func (m *HangupRequest) XXX_Size() int {
	return xxx_messageInfo_HangupRequest.Size(m)
}
func (m *HangupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HangupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HangupRequest proto.InternalMessageInfo

func (m *HangupRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *HangupRequest) GetCause() string {
	if m != nil {
		return m.Cause
	}
	return ""
}

func (m *HangupRequest) GetReporting() bool {
	if m != nil {
		return m.Reporting
	}
	return false
}

type HangupResponse struct {
	Error                *ErrorExecute `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *HangupResponse) Reset()         { *m = HangupResponse{} }
func (m *HangupResponse) String() string { return proto.CompactTextString(m) }
func (*HangupResponse) ProtoMessage()    {}
func (*HangupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e604833c2b457e38, []int{8}
}

func (m *HangupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HangupResponse.Unmarshal(m, b)
}
func (m *HangupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HangupResponse.Marshal(b, m, deterministic)
}
func (m *HangupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HangupResponse.Merge(m, src)
}
func (m *HangupResponse) XXX_Size() int {
	return xxx_messageInfo_HangupResponse.Size(m)
}
func (m *HangupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HangupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HangupResponse proto.InternalMessageInfo

func (m *HangupResponse) GetError() *ErrorExecute {
	if m != nil {
		return m.Error
	}
	return nil
}

type OriginateRequest struct {
	Variables            map[string]string             `protobuf:"bytes,1,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Endpoints            []string                      `protobuf:"bytes,2,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	Strategy             OriginateRequest_Strategy     `protobuf:"varint,3,opt,name=strategy,proto3,enum=fs.OriginateRequest_Strategy" json:"strategy,omitempty"`
	Destination          string                        `protobuf:"bytes,4,opt,name=destination,proto3" json:"destination,omitempty"`
	Timeout              int32                         `protobuf:"varint,5,opt,name=timeout,proto3" json:"timeout,omitempty"`
	CallerNumber         string                        `protobuf:"bytes,6,opt,name=callerNumber,proto3" json:"callerNumber,omitempty"`
	CallerName           string                        `protobuf:"bytes,7,opt,name=callerName,proto3" json:"callerName,omitempty"`
	Context              string                        `protobuf:"bytes,8,opt,name=context,proto3" json:"context,omitempty"`
	Dialplan             string                        `protobuf:"bytes,9,opt,name=dialplan,proto3" json:"dialplan,omitempty"`
	Extensions           []*OriginateRequest_Extension `protobuf:"bytes,10,rep,name=extensions,proto3" json:"extensions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *OriginateRequest) Reset()         { *m = OriginateRequest{} }
func (m *OriginateRequest) String() string { return proto.CompactTextString(m) }
func (*OriginateRequest) ProtoMessage()    {}
func (*OriginateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e604833c2b457e38, []int{9}
}

func (m *OriginateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OriginateRequest.Unmarshal(m, b)
}
func (m *OriginateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OriginateRequest.Marshal(b, m, deterministic)
}
func (m *OriginateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OriginateRequest.Merge(m, src)
}
func (m *OriginateRequest) XXX_Size() int {
	return xxx_messageInfo_OriginateRequest.Size(m)
}
func (m *OriginateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OriginateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OriginateRequest proto.InternalMessageInfo

func (m *OriginateRequest) GetVariables() map[string]string {
	if m != nil {
		return m.Variables
	}
	return nil
}

func (m *OriginateRequest) GetEndpoints() []string {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

func (m *OriginateRequest) GetStrategy() OriginateRequest_Strategy {
	if m != nil {
		return m.Strategy
	}
	return OriginateRequest_FAILOVER
}

func (m *OriginateRequest) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *OriginateRequest) GetTimeout() int32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *OriginateRequest) GetCallerNumber() string {
	if m != nil {
		return m.CallerNumber
	}
	return ""
}

func (m *OriginateRequest) GetCallerName() string {
	if m != nil {
		return m.CallerName
	}
	return ""
}

func (m *OriginateRequest) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

func (m *OriginateRequest) GetDialplan() string {
	if m != nil {
		return m.Dialplan
	}
	return ""
}

func (m *OriginateRequest) GetExtensions() []*OriginateRequest_Extension {
	if m != nil {
		return m.Extensions
	}
	return nil
}

type OriginateRequest_Extension struct {
	AppName              string   `protobuf:"bytes,1,opt,name=appName,proto3" json:"appName,omitempty"`
	Args                 string   `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OriginateRequest_Extension) Reset()         { *m = OriginateRequest_Extension{} }
func (m *OriginateRequest_Extension) String() string { return proto.CompactTextString(m) }
func (*OriginateRequest_Extension) ProtoMessage()    {}
func (*OriginateRequest_Extension) Descriptor() ([]byte, []int) {
	return fileDescriptor_e604833c2b457e38, []int{9, 0}
}

func (m *OriginateRequest_Extension) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OriginateRequest_Extension.Unmarshal(m, b)
}
func (m *OriginateRequest_Extension) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OriginateRequest_Extension.Marshal(b, m, deterministic)
}
func (m *OriginateRequest_Extension) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OriginateRequest_Extension.Merge(m, src)
}
func (m *OriginateRequest_Extension) XXX_Size() int {
	return xxx_messageInfo_OriginateRequest_Extension.Size(m)
}
func (m *OriginateRequest_Extension) XXX_DiscardUnknown() {
	xxx_messageInfo_OriginateRequest_Extension.DiscardUnknown(m)
}

var xxx_messageInfo_OriginateRequest_Extension proto.InternalMessageInfo

func (m *OriginateRequest_Extension) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *OriginateRequest_Extension) GetArgs() string {
	if m != nil {
		return m.Args
	}
	return ""
}

type OriginateResponse struct {
	Uuid                 string        `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Error                *ErrorExecute `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	ErrorCode            int32         `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *OriginateResponse) Reset()         { *m = OriginateResponse{} }
func (m *OriginateResponse) String() string { return proto.CompactTextString(m) }
func (*OriginateResponse) ProtoMessage()    {}
func (*OriginateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e604833c2b457e38, []int{10}
}

func (m *OriginateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OriginateResponse.Unmarshal(m, b)
}
func (m *OriginateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OriginateResponse.Marshal(b, m, deterministic)
}
func (m *OriginateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OriginateResponse.Merge(m, src)
}
func (m *OriginateResponse) XXX_Size() int {
	return xxx_messageInfo_OriginateResponse.Size(m)
}
func (m *OriginateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OriginateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OriginateResponse proto.InternalMessageInfo

func (m *OriginateResponse) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *OriginateResponse) GetError() *ErrorExecute {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *OriginateResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

type BridgeRequest struct {
	LegAId               string   `protobuf:"bytes,1,opt,name=leg_a_id,json=legAId,proto3" json:"leg_a_id,omitempty"`
	LegBId               string   `protobuf:"bytes,2,opt,name=leg_b_id,json=legBId,proto3" json:"leg_b_id,omitempty"`
	LegBReserveId        string   `protobuf:"bytes,3,opt,name=leg_b_reserve_id,json=legBReserveId,proto3" json:"leg_b_reserve_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BridgeRequest) Reset()         { *m = BridgeRequest{} }
func (m *BridgeRequest) String() string { return proto.CompactTextString(m) }
func (*BridgeRequest) ProtoMessage()    {}
func (*BridgeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e604833c2b457e38, []int{11}
}

func (m *BridgeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BridgeRequest.Unmarshal(m, b)
}
func (m *BridgeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BridgeRequest.Marshal(b, m, deterministic)
}
func (m *BridgeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BridgeRequest.Merge(m, src)
}
func (m *BridgeRequest) XXX_Size() int {
	return xxx_messageInfo_BridgeRequest.Size(m)
}
func (m *BridgeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BridgeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BridgeRequest proto.InternalMessageInfo

func (m *BridgeRequest) GetLegAId() string {
	if m != nil {
		return m.LegAId
	}
	return ""
}

func (m *BridgeRequest) GetLegBId() string {
	if m != nil {
		return m.LegBId
	}
	return ""
}

func (m *BridgeRequest) GetLegBReserveId() string {
	if m != nil {
		return m.LegBReserveId
	}
	return ""
}

type BridgeResponse struct {
	Uuid                 string        `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Error                *ErrorExecute `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *BridgeResponse) Reset()         { *m = BridgeResponse{} }
func (m *BridgeResponse) String() string { return proto.CompactTextString(m) }
func (*BridgeResponse) ProtoMessage()    {}
func (*BridgeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e604833c2b457e38, []int{12}
}

func (m *BridgeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BridgeResponse.Unmarshal(m, b)
}
func (m *BridgeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BridgeResponse.Marshal(b, m, deterministic)
}
func (m *BridgeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BridgeResponse.Merge(m, src)
}
func (m *BridgeResponse) XXX_Size() int {
	return xxx_messageInfo_BridgeResponse.Size(m)
}
func (m *BridgeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BridgeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BridgeResponse proto.InternalMessageInfo

func (m *BridgeResponse) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *BridgeResponse) GetError() *ErrorExecute {
	if m != nil {
		return m.Error
	}
	return nil
}

type SetVariablesRequest struct {
	Uuid                 string            `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Variables            map[string]string `protobuf:"bytes,2,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SetVariablesRequest) Reset()         { *m = SetVariablesRequest{} }
func (m *SetVariablesRequest) String() string { return proto.CompactTextString(m) }
func (*SetVariablesRequest) ProtoMessage()    {}
func (*SetVariablesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e604833c2b457e38, []int{13}
}

func (m *SetVariablesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetVariablesRequest.Unmarshal(m, b)
}
func (m *SetVariablesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetVariablesRequest.Marshal(b, m, deterministic)
}
func (m *SetVariablesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetVariablesRequest.Merge(m, src)
}
func (m *SetVariablesRequest) XXX_Size() int {
	return xxx_messageInfo_SetVariablesRequest.Size(m)
}
func (m *SetVariablesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetVariablesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetVariablesRequest proto.InternalMessageInfo

func (m *SetVariablesRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *SetVariablesRequest) GetVariables() map[string]string {
	if m != nil {
		return m.Variables
	}
	return nil
}

type SetVariablesResponse struct {
	Error                *ErrorExecute `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SetVariablesResponse) Reset()         { *m = SetVariablesResponse{} }
func (m *SetVariablesResponse) String() string { return proto.CompactTextString(m) }
func (*SetVariablesResponse) ProtoMessage()    {}
func (*SetVariablesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e604833c2b457e38, []int{14}
}

func (m *SetVariablesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetVariablesResponse.Unmarshal(m, b)
}
func (m *SetVariablesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetVariablesResponse.Marshal(b, m, deterministic)
}
func (m *SetVariablesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetVariablesResponse.Merge(m, src)
}
func (m *SetVariablesResponse) XXX_Size() int {
	return xxx_messageInfo_SetVariablesResponse.Size(m)
}
func (m *SetVariablesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetVariablesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetVariablesResponse proto.InternalMessageInfo

func (m *SetVariablesResponse) GetError() *ErrorExecute {
	if m != nil {
		return m.Error
	}
	return nil
}

type HangupMatchingVarsReqeust struct {
	Cause                string            `protobuf:"bytes,1,opt,name=cause,proto3" json:"cause,omitempty"`
	Variables            map[string]string `protobuf:"bytes,2,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *HangupMatchingVarsReqeust) Reset()         { *m = HangupMatchingVarsReqeust{} }
func (m *HangupMatchingVarsReqeust) String() string { return proto.CompactTextString(m) }
func (*HangupMatchingVarsReqeust) ProtoMessage()    {}
func (*HangupMatchingVarsReqeust) Descriptor() ([]byte, []int) {
	return fileDescriptor_e604833c2b457e38, []int{15}
}

func (m *HangupMatchingVarsReqeust) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HangupMatchingVarsReqeust.Unmarshal(m, b)
}
func (m *HangupMatchingVarsReqeust) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HangupMatchingVarsReqeust.Marshal(b, m, deterministic)
}
func (m *HangupMatchingVarsReqeust) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HangupMatchingVarsReqeust.Merge(m, src)
}
func (m *HangupMatchingVarsReqeust) XXX_Size() int {
	return xxx_messageInfo_HangupMatchingVarsReqeust.Size(m)
}
func (m *HangupMatchingVarsReqeust) XXX_DiscardUnknown() {
	xxx_messageInfo_HangupMatchingVarsReqeust.DiscardUnknown(m)
}

var xxx_messageInfo_HangupMatchingVarsReqeust proto.InternalMessageInfo

func (m *HangupMatchingVarsReqeust) GetCause() string {
	if m != nil {
		return m.Cause
	}
	return ""
}

func (m *HangupMatchingVarsReqeust) GetVariables() map[string]string {
	if m != nil {
		return m.Variables
	}
	return nil
}

type HangupMatchingVarsResponse struct {
	Count                int32    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HangupMatchingVarsResponse) Reset()         { *m = HangupMatchingVarsResponse{} }
func (m *HangupMatchingVarsResponse) String() string { return proto.CompactTextString(m) }
func (*HangupMatchingVarsResponse) ProtoMessage()    {}
func (*HangupMatchingVarsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e604833c2b457e38, []int{16}
}

func (m *HangupMatchingVarsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HangupMatchingVarsResponse.Unmarshal(m, b)
}
func (m *HangupMatchingVarsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HangupMatchingVarsResponse.Marshal(b, m, deterministic)
}
func (m *HangupMatchingVarsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HangupMatchingVarsResponse.Merge(m, src)
}
func (m *HangupMatchingVarsResponse) XXX_Size() int {
	return xxx_messageInfo_HangupMatchingVarsResponse.Size(m)
}
func (m *HangupMatchingVarsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HangupMatchingVarsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HangupMatchingVarsResponse proto.InternalMessageInfo

func (m *HangupMatchingVarsResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterEnum("fs.ErrorExecute_Type", ErrorExecute_Type_name, ErrorExecute_Type_value)
	proto.RegisterEnum("fs.OriginateRequest_Strategy", OriginateRequest_Strategy_name, OriginateRequest_Strategy_value)
	proto.RegisterType((*VoiceStreamRequest)(nil), "fs.VoiceStreamRequest")
	proto.RegisterType((*VoiceStreamRequest_Init)(nil), "fs.VoiceStreamRequest.Init")
	proto.RegisterType((*VoiceStreamRequest_Chunk)(nil), "fs.VoiceStreamRequest.Chunk")
	proto.RegisterType((*VoiceStreamResponse)(nil), "fs.VoiceStreamResponse")
	proto.RegisterType((*VoiceStreamResponse_Chunk)(nil), "fs.VoiceStreamResponse.Chunk")
	proto.RegisterType((*QueueRequest)(nil), "fs.QueueRequest")
	proto.RegisterMapType((map[string]string)(nil), "fs.QueueRequest.VariablesEntry")
	proto.RegisterType((*QueueResponse)(nil), "fs.QueueResponse")
	proto.RegisterType((*ErrorExecute)(nil), "fs.ErrorExecute")
	proto.RegisterType((*ExecuteRequest)(nil), "fs.ExecuteRequest")
	proto.RegisterType((*ExecuteResponse)(nil), "fs.ExecuteResponse")
	proto.RegisterType((*HangupRequest)(nil), "fs.HangupRequest")
	proto.RegisterType((*HangupResponse)(nil), "fs.HangupResponse")
	proto.RegisterType((*OriginateRequest)(nil), "fs.OriginateRequest")
	proto.RegisterMapType((map[string]string)(nil), "fs.OriginateRequest.VariablesEntry")
	proto.RegisterType((*OriginateRequest_Extension)(nil), "fs.OriginateRequest.Extension")
	proto.RegisterType((*OriginateResponse)(nil), "fs.OriginateResponse")
	proto.RegisterType((*BridgeRequest)(nil), "fs.BridgeRequest")
	proto.RegisterType((*BridgeResponse)(nil), "fs.BridgeResponse")
	proto.RegisterType((*SetVariablesRequest)(nil), "fs.SetVariablesRequest")
	proto.RegisterMapType((map[string]string)(nil), "fs.SetVariablesRequest.VariablesEntry")
	proto.RegisterType((*SetVariablesResponse)(nil), "fs.SetVariablesResponse")
	proto.RegisterType((*HangupMatchingVarsReqeust)(nil), "fs.HangupMatchingVarsReqeust")
	proto.RegisterMapType((map[string]string)(nil), "fs.HangupMatchingVarsReqeust.VariablesEntry")
	proto.RegisterType((*HangupMatchingVarsResponse)(nil), "fs.HangupMatchingVarsResponse")
}

func init() { proto.RegisterFile("fs.proto", fileDescriptor_e604833c2b457e38) }

var fileDescriptor_e604833c2b457e38 = []byte{
	// 1042 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0x8e, 0xd3, 0xb8, 0x89, 0x4f, 0x93, 0x90, 0x9d, 0x76, 0x77, 0x8d, 0x69, 0x4b, 0xf1, 0x4a,
	0xa5, 0x48, 0x28, 0x82, 0xb0, 0x68, 0x7f, 0x04, 0x95, 0xd2, 0x6e, 0x96, 0x06, 0xb5, 0x14, 0xa6,
	0xdb, 0x72, 0x59, 0x4d, 0xe2, 0xa9, 0xd7, 0xaa, 0x63, 0x7b, 0xc7, 0xe3, 0xd2, 0x3c, 0x14, 0x4f,
	0xc0, 0x35, 0xbc, 0x09, 0xd7, 0xbc, 0x02, 0x9a, 0x19, 0xdb, 0x71, 0xfe, 0x2a, 0xaa, 0x8a, 0xbb,
	0x39, 0xe7, 0x7c, 0xe7, 0xff, 0x9c, 0x99, 0x81, 0xda, 0x55, 0xdc, 0x8e, 0x58, 0xc8, 0x43, 0x54,
	0xbe, 0x8a, 0xed, 0xbf, 0x34, 0x40, 0x17, 0xa1, 0x37, 0xa4, 0x67, 0x9c, 0x51, 0x32, 0xc2, 0xf4,
	0x43, 0x42, 0x63, 0x8e, 0x5e, 0x40, 0x95, 0xa9, 0xa3, 0xa9, 0xed, 0x68, 0x7b, 0x6b, 0x9d, 0x4f,
	0xda, 0x57, 0x71, 0x7b, 0x1e, 0xd8, 0xee, 0x07, 0x1e, 0x3f, 0x2a, 0xe1, 0x0c, 0x8d, 0x9e, 0x83,
	0x3e, 0x7c, 0x9f, 0x04, 0xd7, 0x66, 0x59, 0xaa, 0x6d, 0x2e, 0x51, 0x3b, 0x14, 0x98, 0xa3, 0x12,
	0x56, 0x60, 0xeb, 0x09, 0x54, 0x84, 0x21, 0xd4, 0x84, 0xb2, 0xe7, 0x48, 0x8f, 0x06, 0x2e, 0x7b,
	0x8e, 0xf5, 0x19, 0xe8, 0x12, 0x89, 0x4c, 0xa8, 0x1e, 0x86, 0x01, 0xa7, 0x81, 0x8a, 0xa7, 0x8e,
	0x33, 0xf2, 0x60, 0x15, 0x2a, 0x0e, 0xe1, 0xc4, 0xfe, 0x0d, 0xd6, 0xa7, 0xfc, 0xc4, 0x51, 0x18,
	0xc4, 0x14, 0x7d, 0x9b, 0xc5, 0xa3, 0xd2, 0xd8, 0x9a, 0x8b, 0x47, 0xe1, 0x66, 0x03, 0xba, 0x87,
	0xe3, 0xbf, 0x35, 0xa8, 0xff, 0x92, 0xd0, 0x84, 0x66, 0xb5, 0x9b, 0x49, 0x02, 0x7d, 0x0f, 0xc6,
	0x0d, 0x61, 0x1e, 0x19, 0xf8, 0x34, 0x36, 0xcb, 0x3b, 0x2b, 0x7b, 0x6b, 0x9d, 0x4f, 0x45, 0x18,
	0x45, 0xa5, 0xf6, 0x45, 0x86, 0xe8, 0x05, 0x9c, 0x8d, 0xf1, 0x44, 0x03, 0x3d, 0x83, 0x46, 0xe4,
	0x93, 0xf1, 0x80, 0x0c, 0xaf, 0x2f, 0xaf, 0x3c, 0x9f, 0x9a, 0x2b, 0xd2, 0x72, 0x3d, 0x63, 0xbe,
	0xf5, 0x7c, 0x3a, 0x05, 0x22, 0xcc, 0x8d, 0xcd, 0xca, 0x8e, 0xb6, 0xa7, 0x4f, 0x40, 0x5d, 0xe6,
	0xc6, 0xd6, 0x77, 0xd0, 0x9c, 0x76, 0x83, 0x5a, 0xb0, 0x72, 0x4d, 0xc7, 0x69, 0xac, 0xe2, 0x88,
	0x36, 0x40, 0xbf, 0x21, 0x7e, 0x42, 0x65, 0xff, 0x0c, 0xac, 0x88, 0xd7, 0xe5, 0x97, 0x9a, 0xfd,
	0x02, 0x1a, 0x69, 0xc4, 0x69, 0x69, 0x77, 0x41, 0xa7, 0x8c, 0x85, 0x2c, 0x2d, 0x6d, 0x4b, 0xe4,
	0xd4, 0x13, 0x8c, 0xde, 0x2d, 0x1d, 0x26, 0x9c, 0x62, 0x25, 0xb6, 0x3f, 0x40, 0xbd, 0xc8, 0x16,
	0x25, 0x1d, 0xd1, 0x38, 0x26, 0x2e, 0x4d, 0x1d, 0x67, 0x24, 0xfa, 0x02, 0x2a, 0x7c, 0x1c, 0x29,
	0xdf, 0xcd, 0xce, 0xe3, 0x59, 0x83, 0xed, 0x77, 0xe3, 0x88, 0x62, 0x09, 0xb1, 0x37, 0xa1, 0x22,
	0x28, 0x64, 0x80, 0xde, 0xc3, 0xf8, 0x14, 0xb7, 0x4a, 0xe2, 0x78, 0x7e, 0xd6, 0xfd, 0xa1, 0xd7,
	0xd2, 0xec, 0x7d, 0x68, 0x66, 0x41, 0xa4, 0x4d, 0x31, 0xa1, 0x3a, 0x0c, 0x47, 0x23, 0x12, 0x64,
	0x9d, 0xc9, 0x48, 0x84, 0xa0, 0x22, 0x2b, 0xa6, 0x12, 0x96, 0x67, 0xfb, 0x04, 0x3e, 0xca, 0xf5,
	0xd3, 0x6c, 0x91, 0x6a, 0x77, 0xaa, 0x2d, 0xcf, 0x93, 0x0a, 0x94, 0xef, 0xae, 0xc0, 0xaf, 0xd0,
	0x38, 0x22, 0x81, 0x9b, 0x44, 0x59, 0x34, 0x08, 0x2a, 0x49, 0x92, 0x0f, 0x89, 0x3c, 0x8b, 0xca,
	0x0f, 0x49, 0x12, 0xe7, 0x95, 0x97, 0x04, 0xda, 0x04, 0x83, 0xd1, 0x28, 0x64, 0xdc, 0x0b, 0x5c,
	0xd9, 0xf9, 0x1a, 0x9e, 0x30, 0xec, 0x97, 0xd0, 0xcc, 0x0c, 0xdf, 0xb3, 0x29, 0x7f, 0x56, 0xa0,
	0x75, 0xca, 0x3c, 0xd7, 0x0b, 0xc8, 0xa4, 0x48, 0xdd, 0xe2, 0xa4, 0x6a, 0x72, 0x52, 0x9f, 0x09,
	0x03, 0xb3, 0xc0, 0x3b, 0xa6, 0x75, 0x13, 0x0c, 0x1a, 0x38, 0x51, 0xe8, 0x05, 0x5c, 0x0d, 0xbb,
	0x81, 0x27, 0x0c, 0xf4, 0x0a, 0x6a, 0x31, 0x67, 0x84, 0x53, 0x77, 0x2c, 0x93, 0x69, 0xaa, 0x85,
	0x9c, 0xb3, 0x7f, 0x96, 0x82, 0x70, 0x0e, 0x47, 0x3b, 0xb0, 0xe6, 0xd0, 0x98, 0x0b, 0x98, 0x17,
	0x06, 0x72, 0xbe, 0x0d, 0x5c, 0x64, 0x89, 0x16, 0x73, 0x6f, 0x44, 0xc3, 0x84, 0x9b, 0xba, 0x9c,
	0xfe, 0x8c, 0x44, 0x36, 0xd4, 0x87, 0xc4, 0xf7, 0x29, 0xfb, 0x29, 0x19, 0x0d, 0x28, 0x33, 0x57,
	0xd5, 0x06, 0x15, 0x79, 0x68, 0x1b, 0x20, 0xa5, 0xc9, 0x88, 0x9a, 0x55, 0x89, 0x28, 0x70, 0xd4,
	0x00, 0x05, 0x9c, 0xde, 0x72, 0xb3, 0x96, 0x0d, 0x90, 0x24, 0x91, 0x05, 0x35, 0xc7, 0x23, 0x7e,
	0xe4, 0x93, 0xc0, 0x34, 0xa4, 0x28, 0xa7, 0xd1, 0x3e, 0x00, 0xbd, 0xe5, 0x34, 0x88, 0xbd, 0x30,
	0x88, 0x4d, 0x90, 0x25, 0xdd, 0x5e, 0x98, 0x72, 0x2f, 0x83, 0xe1, 0x82, 0x86, 0xf5, 0x0a, 0x8c,
	0x5c, 0x20, 0x42, 0x20, 0x51, 0x24, 0xe3, 0x4b, 0x67, 0x38, 0x25, 0x17, 0xcd, 0xf0, 0x03, 0xb7,
	0x7d, 0x17, 0x6a, 0x59, 0x13, 0x50, 0x1d, 0x6a, 0x6f, 0xbb, 0xfd, 0xe3, 0xd3, 0x8b, 0x9e, 0x58,
	0xb3, 0x3a, 0xd4, 0x4e, 0xce, 0x8f, 0xdf, 0xf5, 0x7f, 0x3e, 0x16, 0x9b, 0x16, 0xc0, 0xa3, 0x42,
	0x2a, 0x93, 0x5d, 0x99, 0x1b, 0xef, 0xff, 0xb8, 0x2b, 0x68, 0x0b, 0x40, 0x1e, 0x2e, 0x87, 0xa1,
	0xa3, 0xee, 0x3a, 0x1d, 0x1b, 0x92, 0x73, 0x18, 0x3a, 0xd4, 0xf6, 0xa1, 0x71, 0xc0, 0x3c, 0xc7,
	0x2d, 0x2c, 0x76, 0xcd, 0xa7, 0xee, 0x25, 0xb9, 0xcc, 0xfd, 0xad, 0xfa, 0xd4, 0xed, 0xf6, 0x9d,
	0x4c, 0x32, 0x10, 0x92, 0x72, 0x2e, 0x39, 0xe8, 0x3b, 0xe8, 0x73, 0x68, 0x29, 0x09, 0xa3, 0x31,
	0x65, 0x37, 0x54, 0x20, 0xd4, 0xad, 0xda, 0x10, 0x08, 0xac, 0xb8, 0x7d, 0xc7, 0x3e, 0x86, 0x66,
	0xe6, 0xed, 0xe1, 0xa9, 0xd9, 0xbf, 0x6b, 0xb0, 0x7e, 0x46, 0x79, 0xde, 0x95, 0xbb, 0x6e, 0x83,
	0x37, 0xf3, 0x8f, 0xc6, 0xae, 0xb0, 0xbb, 0x40, 0x7f, 0xf9, 0x36, 0x3e, 0x70, 0x06, 0xf6, 0x61,
	0x63, 0xda, 0xdd, 0x3d, 0xef, 0x98, 0x3f, 0x34, 0xf8, 0x58, 0x5d, 0x4f, 0x27, 0x84, 0x0f, 0xdf,
	0x7b, 0x81, 0x7b, 0x41, 0x98, 0x88, 0x9a, 0x26, 0x31, 0x9f, 0xdc, 0x77, 0x5a, 0xf1, 0xbe, 0xfb,
	0x71, 0x3e, 0xef, 0x2f, 0x85, 0xfd, 0xa5, 0x76, 0xfe, 0xb7, 0xec, 0x3b, 0x60, 0x2d, 0x72, 0x9a,
	0xd6, 0x40, 0x44, 0x1f, 0x26, 0xe9, 0xaf, 0x40, 0xc7, 0x8a, 0xe8, 0xfc, 0xb3, 0x02, 0x2b, 0xdd,
	0xc8, 0x43, 0xaf, 0xc1, 0xc8, 0xb7, 0x02, 0x6d, 0x2c, 0xda, 0x77, 0xeb, 0xf1, 0x0c, 0x57, 0xd9,
	0xb5, 0x4b, 0xe8, 0x39, 0x54, 0xb3, 0x97, 0x12, 0xc9, 0xca, 0x4e, 0x3d, 0x64, 0xd6, 0xfa, 0x14,
	0x2f, 0xd7, 0x3a, 0x84, 0x7a, 0xb1, 0x57, 0xe8, 0xe9, 0x92, 0x61, 0xb1, 0xcc, 0x79, 0x41, 0x6e,
	0xe4, 0x6b, 0x58, 0x55, 0xe3, 0x8e, 0x1e, 0x09, 0xd4, 0xd4, 0xa2, 0x59, 0xa8, 0xc8, 0x2a, 0xaa,
	0xa8, 0x2a, 0x29, 0x95, 0xa9, 0x67, 0x4e, 0xa9, 0x4c, 0x3f, 0x50, 0x76, 0x09, 0x9d, 0x03, 0x9a,
	0x2f, 0x2c, 0xda, 0xba, 0xb3, 0xcb, 0xd6, 0xf6, 0x32, 0x71, 0x6e, 0xb6, 0x0d, 0xba, 0xfc, 0x9f,
	0xa0, 0xd6, 0xec, 0xe7, 0xca, 0x7a, 0x54, 0xe0, 0xe4, 0xf8, 0x37, 0xb0, 0x56, 0xf8, 0x08, 0xa2,
	0x27, 0x8b, 0x7f, 0xaa, 0xd6, 0xd3, 0x25, 0x3f, 0x46, 0xbb, 0xb4, 0xa7, 0x7d, 0xa5, 0x0d, 0x56,
	0xe5, 0x57, 0xfa, 0x9b, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xe8, 0x81, 0xfc, 0x19, 0x56, 0x0b,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ApiClient is the client API for Api service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ApiClient interface {
	Originate(ctx context.Context, in *OriginateRequest, opts ...grpc.CallOption) (*OriginateResponse, error)
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
	SetVariables(ctx context.Context, in *SetVariablesRequest, opts ...grpc.CallOption) (*SetVariablesResponse, error)
	Bridge(ctx context.Context, in *BridgeRequest, opts ...grpc.CallOption) (*BridgeResponse, error)
	Hangup(ctx context.Context, in *HangupRequest, opts ...grpc.CallOption) (*HangupResponse, error)
	HangupMatchingVars(ctx context.Context, in *HangupMatchingVarsReqeust, opts ...grpc.CallOption) (*HangupMatchingVarsResponse, error)
	Queue(ctx context.Context, in *QueueRequest, opts ...grpc.CallOption) (*QueueResponse, error)
	VoiceStream(ctx context.Context, opts ...grpc.CallOption) (Api_VoiceStreamClient, error)
}

type apiClient struct {
	cc *grpc.ClientConn
}

func NewApiClient(cc *grpc.ClientConn) ApiClient {
	return &apiClient{cc}
}

func (c *apiClient) Originate(ctx context.Context, in *OriginateRequest, opts ...grpc.CallOption) (*OriginateResponse, error) {
	out := new(OriginateResponse)
	err := c.cc.Invoke(ctx, "/fs.Api/Originate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, "/fs.Api/Execute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) SetVariables(ctx context.Context, in *SetVariablesRequest, opts ...grpc.CallOption) (*SetVariablesResponse, error) {
	out := new(SetVariablesResponse)
	err := c.cc.Invoke(ctx, "/fs.Api/SetVariables", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Bridge(ctx context.Context, in *BridgeRequest, opts ...grpc.CallOption) (*BridgeResponse, error) {
	out := new(BridgeResponse)
	err := c.cc.Invoke(ctx, "/fs.Api/Bridge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Hangup(ctx context.Context, in *HangupRequest, opts ...grpc.CallOption) (*HangupResponse, error) {
	out := new(HangupResponse)
	err := c.cc.Invoke(ctx, "/fs.Api/Hangup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) HangupMatchingVars(ctx context.Context, in *HangupMatchingVarsReqeust, opts ...grpc.CallOption) (*HangupMatchingVarsResponse, error) {
	out := new(HangupMatchingVarsResponse)
	err := c.cc.Invoke(ctx, "/fs.Api/HangupMatchingVars", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Queue(ctx context.Context, in *QueueRequest, opts ...grpc.CallOption) (*QueueResponse, error) {
	out := new(QueueResponse)
	err := c.cc.Invoke(ctx, "/fs.Api/Queue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) VoiceStream(ctx context.Context, opts ...grpc.CallOption) (Api_VoiceStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Api_serviceDesc.Streams[0], "/fs.Api/VoiceStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &apiVoiceStreamClient{stream}
	return x, nil
}

type Api_VoiceStreamClient interface {
	Send(*VoiceStreamRequest) error
	Recv() (*VoiceStreamResponse, error)
	grpc.ClientStream
}

type apiVoiceStreamClient struct {
	grpc.ClientStream
}

func (x *apiVoiceStreamClient) Send(m *VoiceStreamRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *apiVoiceStreamClient) Recv() (*VoiceStreamResponse, error) {
	m := new(VoiceStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ApiServer is the server API for Api service.
type ApiServer interface {
	Originate(context.Context, *OriginateRequest) (*OriginateResponse, error)
	Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
	SetVariables(context.Context, *SetVariablesRequest) (*SetVariablesResponse, error)
	Bridge(context.Context, *BridgeRequest) (*BridgeResponse, error)
	Hangup(context.Context, *HangupRequest) (*HangupResponse, error)
	HangupMatchingVars(context.Context, *HangupMatchingVarsReqeust) (*HangupMatchingVarsResponse, error)
	Queue(context.Context, *QueueRequest) (*QueueResponse, error)
	VoiceStream(Api_VoiceStreamServer) error
}

// UnimplementedApiServer can be embedded to have forward compatible implementations.
type UnimplementedApiServer struct {
}

func (*UnimplementedApiServer) Originate(ctx context.Context, req *OriginateRequest) (*OriginateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Originate not implemented")
}
func (*UnimplementedApiServer) Execute(ctx context.Context, req *ExecuteRequest) (*ExecuteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (*UnimplementedApiServer) SetVariables(ctx context.Context, req *SetVariablesRequest) (*SetVariablesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetVariables not implemented")
}
func (*UnimplementedApiServer) Bridge(ctx context.Context, req *BridgeRequest) (*BridgeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Bridge not implemented")
}
func (*UnimplementedApiServer) Hangup(ctx context.Context, req *HangupRequest) (*HangupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hangup not implemented")
}
func (*UnimplementedApiServer) HangupMatchingVars(ctx context.Context, req *HangupMatchingVarsReqeust) (*HangupMatchingVarsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HangupMatchingVars not implemented")
}
func (*UnimplementedApiServer) Queue(ctx context.Context, req *QueueRequest) (*QueueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Queue not implemented")
}
func (*UnimplementedApiServer) VoiceStream(srv Api_VoiceStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method VoiceStream not implemented")
}

func RegisterApiServer(s *grpc.Server, srv ApiServer) {
	s.RegisterService(&_Api_serviceDesc, srv)
}

func _Api_Originate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OriginateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Originate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.Api/Originate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Originate(ctx, req.(*OriginateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.Api/Execute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Execute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_SetVariables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetVariablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).SetVariables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.Api/SetVariables",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).SetVariables(ctx, req.(*SetVariablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_Bridge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BridgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Bridge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.Api/Bridge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Bridge(ctx, req.(*BridgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_Hangup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HangupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Hangup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.Api/Hangup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Hangup(ctx, req.(*HangupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_HangupMatchingVars_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HangupMatchingVarsReqeust)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).HangupMatchingVars(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.Api/HangupMatchingVars",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).HangupMatchingVars(ctx, req.(*HangupMatchingVarsReqeust))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_Queue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Queue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.Api/Queue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Queue(ctx, req.(*QueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_VoiceStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ApiServer).VoiceStream(&apiVoiceStreamServer{stream})
}

type Api_VoiceStreamServer interface {
	Send(*VoiceStreamResponse) error
	Recv() (*VoiceStreamRequest, error)
	grpc.ServerStream
}

type apiVoiceStreamServer struct {
	grpc.ServerStream
}

func (x *apiVoiceStreamServer) Send(m *VoiceStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *apiVoiceStreamServer) Recv() (*VoiceStreamRequest, error) {
	m := new(VoiceStreamRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Api_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fs.Api",
	HandlerType: (*ApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Originate",
			Handler:    _Api_Originate_Handler,
		},
		{
			MethodName: "Execute",
			Handler:    _Api_Execute_Handler,
		},
		{
			MethodName: "SetVariables",
			Handler:    _Api_SetVariables_Handler,
		},
		{
			MethodName: "Bridge",
			Handler:    _Api_Bridge_Handler,
		},
		{
			MethodName: "Hangup",
			Handler:    _Api_Hangup_Handler,
		},
		{
			MethodName: "HangupMatchingVars",
			Handler:    _Api_HangupMatchingVars_Handler,
		},
		{
			MethodName: "Queue",
			Handler:    _Api_Queue_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "VoiceStream",
			Handler:       _Api_VoiceStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "fs.proto",
}
