// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type FlowSessionCheckpoint struct {
	ID           string
	ConnectionID string
	DomainID     int64
	Channel      int16
	SchemaID     int32
	AppID        string
	Variables    pqtype.NullRawMessage
	Status       string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	ClosedAt     sql.NullTime
}
