// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session_checkpoint.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/sqlc-dev/pqtype"
)

const claimOrphaned = `-- name: ClaimOrphaned :many
UPDATE flow.session_checkpoint
   SET app_id = $1, updated_at = now()
 WHERE status = 'active' AND updated_at < $2
RETURNING id, connection_id, domain_id, channel, schema_id, app_id,
          variables, status, created_at, updated_at, closed_at
`

type ClaimOrphanedParams struct {
	AppID     string
	UpdatedAt time.Time
}

func (q *Queries) ClaimOrphaned(ctx context.Context, arg ClaimOrphanedParams) ([]FlowSessionCheckpoint, error) {
	rows, err := q.db.QueryContext(ctx, claimOrphaned, arg.AppID, arg.UpdatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FlowSessionCheckpoint
	for rows.Next() {
		var i FlowSessionCheckpoint
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.DomainID,
			&i.Channel,
			&i.SchemaID,
			&i.AppID,
			&i.Variables,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const closeCheckpoint = `-- name: CloseCheckpoint :exec
UPDATE flow.session_checkpoint
   SET status = 'closed', closed_at = now(), updated_at = now()
 WHERE connection_id = $1 AND status = 'active'
`

func (q *Queries) CloseCheckpoint(ctx context.Context, connectionID string) error {
	_, err := q.db.ExecContext(ctx, closeCheckpoint, connectionID)
	return err
}

const insertCheckpoint = `-- name: InsertCheckpoint :one
INSERT INTO flow.session_checkpoint
    (connection_id, domain_id, channel, schema_id, app_id, variables, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id
`

type InsertCheckpointParams struct {
	ConnectionID string
	DomainID     int64
	Channel      int16
	SchemaID     int32
	AppID        string
	Variables    pqtype.NullRawMessage
	Status       string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) InsertCheckpoint(ctx context.Context, arg InsertCheckpointParams) (string, error) {
	row := q.db.QueryRowContext(ctx, insertCheckpoint,
		arg.ConnectionID,
		arg.DomainID,
		arg.Channel,
		arg.SchemaID,
		arg.AppID,
		arg.Variables,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const listActiveByApp = `-- name: ListActiveByApp :many
SELECT id, connection_id, domain_id, channel, schema_id, app_id,
       variables, status, created_at, updated_at, closed_at
  FROM flow.session_checkpoint
 WHERE app_id = $1 AND status = 'active'
`

func (q *Queries) ListActiveByApp(ctx context.Context, appID string) ([]FlowSessionCheckpoint, error) {
	rows, err := q.db.QueryContext(ctx, listActiveByApp, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FlowSessionCheckpoint
	for rows.Next() {
		var i FlowSessionCheckpoint
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.DomainID,
			&i.Channel,
			&i.SchemaID,
			&i.AppID,
			&i.Variables,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchByApp = `-- name: TouchByApp :exec
UPDATE flow.session_checkpoint
   SET updated_at = now()
 WHERE app_id = $1 AND status = 'active'
`

func (q *Queries) TouchByApp(ctx context.Context, appID string) error {
	_, err := q.db.ExecContext(ctx, touchByApp, appID)
	return err
}

const updateCheckpointVars = `-- name: UpdateCheckpointVars :exec
UPDATE flow.session_checkpoint
   SET variables = $2, updated_at = $3
 WHERE id = $1
`

type UpdateCheckpointVarsParams struct {
	ID        string
	Variables pqtype.NullRawMessage
	UpdatedAt time.Time
}

func (q *Queries) UpdateCheckpointVars(ctx context.Context, arg UpdateCheckpointVarsParams) error {
	_, err := q.db.ExecContext(ctx, updateCheckpointVars, arg.ID, arg.Variables, arg.UpdatedAt)
	return err
}
